import type { ExerciseData } from "../types";

export const topicExercises: ExerciseData[] = [
  {
    "id": 70,
    "title": "Variables: Asignación básica",
    "description": "Tu personaje de Roblox tiene 999 Robux. ¿Cómo guardas ese valor en Python?",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "Tu personaje de Roblox tiene 999 Robux. ¿Cómo guardas ese valor en Python?",
    "options": [
      "var robux = 999",
      "robux = 999",
      "int robux = 999",
      "robux == 999"
    ],
    "hint": "Pista: Revisa los conceptos de Asignación básica.",
    "explanation": "¡Python no usa 'var' ni tipos! Solo nombre = valor. El = es asignación, el == es comparación. Nada de robux == 999 que eso es una pregunta, no un guardado 💎",
    "correctAnswer": "robux = 999",
    "orderIndex": 70,
    "coins": 5,
    "xp": 10,
    "theme": "🎮 Roblox",
    "pytoReaction": "¡Exacto! Pylearn aprueba tu código, Robloxero 🐍"
  },
  {
    "id": 71,
    "title": "Variables: Asignación básica",
    "description": "Tu cuenta de TikTok explotó. ¿Qué número sale en pantalla?",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "seguidores = 2000000\nlikes_totales = 50000000\nprint(seguidores)",
    "options": [
      "2000000",
      "50000000",
      "seguidores",
      "2000000 50000000"
    ],
    "hint": "Pista: Revisa los conceptos de Asignación básica.",
    "explanation": "print() imprime el VALOR de la variable, no su nombre. Como solo llamamos print(seguidores), sale 2000000. ¡Los 50M de likes esperan su turno! 📱",
    "correctAnswer": "2000000",
    "orderIndex": 71,
    "coins": 5,
    "xp": 10,
    "theme": "📱 TikTok",
    "pytoReaction": "¡Eso es! Pylearn también quiere 2M de seguidores 🐍✨"
  },
  {
    "id": 72,
    "title": "Variables: Tipos de datos",
    "description": "El delivery tiene 3 pizzas disponibles. ¿Qué tipo de dato es el número 3?",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "El delivery tiene 3 pizzas disponibles. ¿Qué tipo de dato es el número 3?",
    "options": [
      "str",
      "float",
      "int",
      "bool"
    ],
    "hint": "Pista: Revisa los conceptos de Tipos de datos.",
    "explanation": "int = número entero (sin decimales). float = número decimal (3.5). str = texto ('hola'). bool = True/False. Tres pizzas son 3 unidades completas → int 🍕",
    "correctAnswer": "int",
    "orderIndex": 72,
    "coins": 5,
    "xp": 10,
    "theme": "🍕 Delivery a domicilio",
    "pytoReaction": "¡Correcto! Pylearn pide 3 pizzas más para celebrar 🍕"
  },
  {
    "id": 73,
    "title": "Variables: Asignación básica",
    "description": "El participante 456 tiene un bug en su código. ¿Cuál línea está mal?",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "bug",
    "question": "nombre = \"Seong\"\npremio = \"45.6 millones\"\n456 = participante\nprint(nombre)",
    "options": [
      "nombre = \"Seong\"",
      "premio = \"45.6 millones\"",
      "456 = participante",
      "print(nombre)"
    ],
    "hint": "Pista: Revisa los conceptos de Asignación básica.",
    "explanation": "¡Las variables siempre van a la IZQUIERDA del =! No puedes asignar algo a un número. Correcto: participante = 456. ¡El 456 sobrevivió pero su código no! 🎯",
    "correctAnswer": "456 = participante",
    "orderIndex": 73,
    "coins": 5,
    "xp": 10,
    "theme": "🦑 Squid Game",
    "pytoReaction": "¡Bien visto! Pylearn hubiera eliminado esa línea 🐍"
  },
  {
    "id": 74,
    "title": "Variables: Tipos de datos",
    "description": "El jugador Kylian Mbappé fue fichado por 250.5 millones de dólares. Además, es considerado por muchos como un claro merecedor del Balón de Oro. Completa los datos en la ficha técnica de Python usando los tipos de datos correctos según esta información. ¡Pon a prueba tu conocimiento!",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "jugador = ___\nfichaje_millones = ___\nes_balon_de_oro = ___",
    "options": [
      "\"Mbappé\"",
      "250.5",
      "True",
      "False",
      "250",
      "Mbappé",
      "\"250\""
    ],
    "hint": "Pista: Revisa los conceptos de Tipos de datos.",
    "explanation": "Strings van con comillas (\"Mbappé\"), decimales sin comillas (250.5 no \"250.5\"), y booleanos con mayúscula (True no 'true'). ¡La ficha está lista! ⚽",
    "correctAnswer": "\"Mbappé\",250.5,True",
    "orderIndex": 74,
    "coins": 5,
    "xp": 10,
    "theme": "⚽ Fichaje millonario",
    "pytoReaction": "¡Crack! Tu ficha técnica es perfecta 🐍⚽"
  },
  {
    "id": 75,
    "title": "Variables: Conversión de tipos",
    "description": "ChatGPT recibe el número de tokens como texto pero necesita sumar. ¿Cómo convierte el string '1500' a número entero?",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "tokens = \"1500\"\n# Convertir para poder sumar",
    "options": [
      "tokens.toInt()",
      "int(tokens)",
      "Integer(tokens)",
      "tokens.parse()"
    ],
    "hint": "Pista: Revisa los conceptos de Conversión de tipos.",
    "explanation": "int() convierte strings de números enteros a int. Si el string tiene decimales usa float(). Si quieres texto: str(). ¡Los tokens de ChatGPT ya pueden sumarse! 🤖",
    "correctAnswer": "int(tokens)",
    "orderIndex": 75,
    "coins": 5,
    "xp": 10,
    "theme": "🤖 ChatGPT contando tokens",
    "pytoReaction": "¡Conversión exitosa! Ahora ChatGPT puede calcular su propia factura 🐍"
  },
  {
    "id": 76,
    "title": "Variables: Conversión de tipos",
    "description": "¿Qué imprime la caja registradora de la pastelería?",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "precio = \"12\"\ncantidad = \"3\"\ntotal = int(precio) * int(cantidad)\nprint(f\"Total: S/{total}\")",
    "options": [
      "Total: S/123",
      "Total: S/36",
      "Total: S/12 * 3",
      "Error: no se puede multiplicar strings"
    ],
    "hint": "Pista: Revisa los conceptos de Conversión de tipos.",
    "explanation": "int() convierte los strings antes de multiplicar. Sin int(), \"12\" * \"3\" daría error. 12 × 3 = 36. ¡La pastelería de Pylearn factura bien! 🧁",
    "correctAnswer": "Total: S/36",
    "orderIndex": 76,
    "coins": 5,
    "xp": 10,
    "theme": "🧁 Pastelería de Pylearn",
    "pytoReaction": "¡36 soles! Pylearn vendió todos los croissants 🐍🥐"
  },
  {
    "id": 77,
    "title": "Variables: Augmented assignment",
    "description": "El contador de victorias de Pylearn en Fortnite tiene un bug. ¿Cuál es?",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "bug",
    "question": "victorias = 0\nvictorias =+ 1\nvictorias =+ 1\nprint(victorias)",
    "options": [
      "victorias no puede ser 0 al inicio",
      "=+ no existe, debería ser +=",
      "print necesita comillas alrededor de victorias",
      "No hay bug, imprime 2"
    ],
    "hint": "Pista: Revisa los conceptos de Augmented assignment.",
    "explanation": "=+ no es un operador: hace victorias = (+1) = 1 cada vez, nunca acumula. El correcto es +=, que suma al valor actual. Resultado correcto con +=: victorias sería 2 después de dos victorias 🎮",
    "correctAnswer": "=+ no existe, debería ser +=",
    "orderIndex": 77,
    "coins": 5,
    "xp": 10,
    "theme": "🎮 Fortnite — acumulando victorias",
    "pytoReaction": "¡Bug eliminado! Pylearn ya tiene 2 victorias reales 🐍🏆"
  },
  {
    "id": 78,
    "title": "Variables: Augmented assignment",
    "description": "Goku sube su poder con cada entrenamiento. Completa el operador correcto:",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "poder = 9000\npoder ___ 1000\nprint(poder)  # → 10000",
    "options": [
      "+=",
      "=+",
      "+",
      "= +",
      "++",
      "add="
    ],
    "hint": "Pista: Revisa los conceptos de Augmented assignment.",
    "explanation": "+= es el augmented assignment: poder += 1000 es lo mismo que poder = poder + 1000. También existen -= *= /=. ¡El poder de Goku ya pasa los 10,000! ⚡",
    "correctAnswer": "+=",
    "orderIndex": 78,
    "coins": 5,
    "xp": 10,
    "theme": "⚡ Goku acumulando poder",
    "pytoReaction": "¡¡IT'S OVER 10,000!! Pylearn no puede leer el medidor 🐍⚡"
  },
  {
    "id": 79,
    "title": "Variables: None",
    "description": "Pylearn busca el tesoro pero la función no retorna nada. ¿Qué valor tiene 'resultado'?",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "def buscar_tesoro():\n    print(\"Buscando...\")\n\nresultado = buscar_tesoro()",
    "options": [
      "0",
      "\"\"",
      "None",
      "False"
    ],
    "hint": "Pista: Revisa los conceptos de None.",
    "explanation": "Cuando una función no tiene return (o tiene return sin valor), Python automáticamente devuelve None. None es la ausencia de valor — no es 0 ni vacío. ¡El tesoro no existe! 🦊",
    "correctAnswer": "None",
    "orderIndex": 79,
    "coins": 5,
    "xp": 10,
    "theme": "🦊 El zorro que no encontró nada",
    "pytoReaction": "¡None encontrado! El zorro Pylearn sigue buscando 🐍🦊"
  },
  {
    "id": 80,
    "title": "Variables: None",
    "description": "¿Qué imprime la audición fallida?",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "papel = None\nif papel is None:\n    print(\"Sin papel aún\")\nelse:\n    print(f\"Papel: {papel}\")",
    "options": [
      "None",
      "False",
      "Sin papel aún",
      "Error: papel es None"
    ],
    "hint": "Pista: Revisa los conceptos de None.",
    "explanation": "Para verificar None se usa 'is None' (no ==). Es la forma idiomática de Python. Como papel es None, entra al if y muestra 'Sin papel aún'. ¡El actor Pylearn sigue esperando su gran rol! 🎭",
    "correctAnswer": "Sin papel aún",
    "orderIndex": 80,
    "coins": 5,
    "xp": 10,
    "theme": "🎭 El actor sin papel",
    "pytoReaction": "¡Pylearn practicó Shakespeare para nada! 🐍🎭"
  },
  {
    "id": 81,
    "title": "Variables: Conversión de tipos",
    "description": "La NASA necesita saber el tipo exacto del dato antes de calcular la órbita. ¿Qué retorna type(3.14)?",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "La NASA necesita saber el tipo exacto del dato antes de calcular la órbita. ¿Qué retorna type(3.14)?",
    "options": [
      "int",
      "str",
      "<class 'float'>",
      "number"
    ],
    "hint": "Pista: Revisa los conceptos de Conversión de tipos.",
    "explanation": "type() retorna el tipo como objeto de clase. Se muestra como <class 'float'>, no solo 'float'. Para comparar: type(x) == float o mejor isinstance(x, float). ¡La NASA confía en float para sus cálculos! 🌙",
    "correctAnswer": "<class 'float'>",
    "orderIndex": 81,
    "coins": 5,
    "xp": 10,
    "theme": "🌙 NASA calculando órbita",
    "pytoReaction": "¡Órbita calculada con float! Pylearn va al espacio 🐍🚀"
  },
  {
    "id": 82,
    "title": "Variables: Múltiple asignación",
    "description": "El chef asigna tres ingredientes a la vez en una sola línea:",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "arroz, ___, alga = \"koshihikari\", \"salmón\", \"nori\"\nprint(pescado)  # → salmón",
    "options": [
      "pescado",
      "\"pescado\"",
      "fish",
      "ingrediente2",
      "var2"
    ],
    "hint": "Pista: Revisa los conceptos de Múltiple asignación.",
    "explanation": "La asignación múltiple (unpacking) asigna cada valor en orden. arroz=\"koshihikari\", pescado=\"salmón\", alga=\"nori\". Variables sin comillas — las comillas son solo para strings literales. 🍣",
    "correctAnswer": "pescado",
    "orderIndex": 82,
    "coins": 5,
    "xp": 10,
    "theme": "🍣 Combo de sushi",
    "pytoReaction": "¡Sushi de Pylearn listo! El chef más pythónico de Japón 🐍🍣"
  },
  {
    "id": 83,
    "title": "Variables: Augmented assignment",
    "description": "¿Cuántos puntos tiene el surfista al final?",
    "topic": "Variables básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "puntos = 100\npuntos += 50\npuntos -= 20\npuntos *= 2\nprint(puntos)",
    "options": [
      "260",
      "230",
      "130",
      "150"
    ],
    "hint": "Pista: Revisa los conceptos de Augmented assignment.",
    "explanation": "100 + 50 = 150. 150 - 20 = 130. 130 × 2 = 260. Cada operación modifica el valor actual. Los augmented assignments son la cadena de maniobras del surfista 🏄",
    "correctAnswer": "260",
    "orderIndex": 83,
    "coins": 5,
    "xp": 10,
    "theme": "🏄 Surfista acumulando puntos",
    "pytoReaction": "¡260 puntos! Pylearn hace el tubo perfecto 🐍🏄"
  }
];

