import type { ExerciseData } from "../types";

export const topicExercises: ExerciseData[] = [
  {
    "id": 84,
    "title": "Variables: Conversión de tipos",
    "description": "El bot de Discord necesita mostrar el número de miembros como texto. ¿Qué función usa?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "miembros = 42750\nmensaje = \"El servidor tiene \" + ___ + \" miembros\"",
    "options": [
      "int(miembros)",
      "miembros.toString()",
      "str(miembros)",
      "string(miembros)"
    ],
    "hint": "Pista: Revisa los conceptos de Conversión de tipos.",
    "explanation": "str() convierte cualquier valor a string. Para concatenar con + ambos deben ser string. Alternativa más elegante: f-string f\"El servidor tiene {miembros} miembros\". ¡El bot de Pylearn funciona! 💬",
    "correctAnswer": "str(miembros)",
    "orderIndex": 84,
    "coins": 5,
    "xp": 10,
    "theme": "💬 Discord — bot de bienvenida",
    "pytoReaction": "¡42,750 miembros y creciendo! El server de Pylearn explota 🐍💬"
  },
  {
    "id": 85,
    "title": "Variables: Conversión de tipos",
    "description": "El hechizo numérico de Pylearn falla al lanzarse. ¿Por qué?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "beginner",
    "type": "bug",
    "question": "poder_magico = \"750\"\nboost = 250\ntotal = poder_magico + boost\nprint(f\"Poder final: {total}\")",
    "options": [
      "poder_magico debería ser número, no string",
      "boost no puede ser 250",
      "No se puede usar f-string con números",
      "El variable debe llamarse poder"
    ],
    "hint": "Pista: Revisa los conceptos de Conversión de tipos.",
    "explanation": "No puedes sumar str + int directamente. Python no convierte automáticamente. Fix: int(poder_magico) + boost = 1000. ¡El hechizo de Pylearn necesita tipos correctos! 🧙",
    "correctAnswer": "poder_magico debería ser número, no string",
    "orderIndex": 85,
    "coins": 5,
    "xp": 10,
    "theme": "🧙 Hechizo de Harry Potter fallido",
    "pytoReaction": "¡Expecto Patronum corregido! Pylearn convirtió el string 🐍🧙"
  },
  {
    "id": 86,
    "title": "Variables: Constantes (convención)",
    "description": "En Python, las constantes se escriben en MAYÚSCULAS por convención. Completa:",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "___ = 299792458\nprint(f\"Velocidad de la luz: {VELOCIDAD_LUZ} m/s\")",
    "options": [
      "VELOCIDAD_LUZ",
      "velocidad_luz",
      "VelocidadLuz",
      "const_velocidad",
      "VELOCIDAD"
    ],
    "hint": "Pista: Revisa los conceptos de Constantes (convención).",
    "explanation": "Python no tiene constantes reales, pero por convención se usan MAYÚSCULAS_CON_GUION para indicar 'no modificar'. Es un contrato entre programadores, no una restricción técnica. ¡La NASA respeta las convenciones! 🚀",
    "correctAnswer": "VELOCIDAD_LUZ",
    "orderIndex": 86,
    "coins": 5,
    "xp": 10,
    "theme": "🚀 NASA — velocidad de la luz",
    "pytoReaction": "¡299,792,458 m/s! Pylearn viaja a la velocidad de la luz 🐍🚀"
  },
  {
    "id": 87,
    "title": "Variables: Booleanos",
    "description": "¿Qué valor tienen estas variables booleanas de Halloween?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "es_vampiro = True\nes_de_dia = False\npuede_salir = es_vampiro and not es_de_dia\nprint(puede_salir)",
    "options": [
      "True",
      "False",
      "None",
      "Error"
    ],
    "hint": "Pista: Revisa los conceptos de Booleanos.",
    "explanation": "not es_de_dia = not False = True. True and True = True. El vampiro SÍ puede salir (es vampiro = True, no es de día = True). ¡Pylearn como vampiro aprueba esta lógica! 🎃",
    "correctAnswer": "True",
    "orderIndex": 87,
    "coins": 5,
    "xp": 10,
    "theme": "🎃 Halloween — ¿Es un monstruo?",
    "pytoReaction": "¡El vampiro Pylearn sale a trick-or-treat! 🐍🧛"
  },
  {
    "id": 88,
    "title": "Variables: Asignación básica",
    "description": "¿Cuál es la forma PYTHÓNICA de intercambiar los roles del impostor y el inocente?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "multiple_choice",
    "question": "rol_pyto = \"impostor\"\nrol_ana = \"inocente\"",
    "options": [
      "rol_pyto = rol_ana\nrol_ana = rol_pyto",
      "temp = rol_pyto\nrol_pyto = rol_ana\nrol_ana = temp",
      "rol_pyto, rol_ana = rol_ana, rol_pyto",
      "swap(rol_pyto, rol_ana)"
    ],
    "hint": "Pista: Revisa los conceptos de Asignación básica.",
    "explanation": "¡Python permite swap en UNA línea! a, b = b, a. La opción con 'temp' funciona pero no es pythónica. swap() no existe en Python. ¡Era Pylearn el impostor todo el tiempo! 🔪",
    "correctAnswer": "rol_pyto, rol_ana = rol_ana, rol_pyto",
    "orderIndex": 88,
    "coins": 12,
    "xp": 20,
    "theme": "🎮 Among Us",
    "pytoReaction": "¡Sus! Ahora Pylearn es inocente... o no? 🐍🕵️"
  },
  {
    "id": 89,
    "title": "Variables: Operaciones con variables",
    "description": "¿Cuánto paga el cliente en la taquería de Pylearn?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "predict_output",
    "question": "tacos = 3\nprecio_taco = 15\nrefresco = 8\ndescuento = 5\ntotal = tacos * precio_taco + refresco - descuento\nprint(f\"Total: S/{total}\")",
    "options": [
      "Total: S/45",
      "Total: S/48",
      "Total: S/50",
      "Total: S/28"
    ],
    "hint": "Pista: Revisa los conceptos de Operaciones con variables.",
    "explanation": "3*15=45, más 8=53, menos 5=48. Python respeta el orden de operaciones: primero * y / luego + y -. ¡Los tacos de Pylearn son una ganga! 🌮",
    "correctAnswer": "Total: S/48",
    "orderIndex": 89,
    "coins": 12,
    "xp": 20,
    "theme": "🌮 Taquería de Pylearn",
    "pytoReaction": "¡Exacto! Y además incluye salsa gratis 🐍🌮"
  },
  {
    "id": 90,
    "title": "Variables: Naming de variables",
    "description": "¿Cuál nombre de variable NO es válido en Python?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "multiple_choice",
    "question": "¿Cuál nombre de variable NO es válido en Python?",
    "options": [
      "_terminator",
      "robot_2024",
      "2robots_malvados",
      "robotV2"
    ],
    "hint": "Pista: Revisa los conceptos de Naming de variables.",
    "explanation": "¡Las variables NO pueden empezar con número! Sí pueden tener números en el medio (robot_2024) o al final (robotV2). _terminator también es válida (guion bajo está permitido). ¡Skynet rechazó tu código! 🤖",
    "correctAnswer": "2robots_malvados",
    "orderIndex": 90,
    "coins": 12,
    "xp": 20,
    "theme": "🤖 Skynet lo rechaza",
    "pytoReaction": "¡Buen ojo! Pylearn sobrevivió a Skynet 🐍🤖"
  },
  {
    "id": 91,
    "title": "Variables: Operadores de comparación encadenados",
    "description": "¿Qué diagnóstico da el doctor Pylearn?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "predict_output",
    "question": "temperatura = 38.5\ntiene_fiebre = 37.5 < temperatura < 39.5\nprint(\"Fiebre leve\" if tiene_fiebre else \"Sin fiebre\")",
    "options": [
      "Sin fiebre",
      "Fiebre leve",
      "True",
      "Error: no se pueden encadenar comparaciones"
    ],
    "hint": "Pista: Revisa los conceptos de Operadores de comparación encadenados.",
    "explanation": "Python permite comparaciones encadenadas: 37.5 < 38.5 < 39.5 es equivalente a (37.5 < 38.5) and (38.5 < 39.5) = True. Más legible que en otros lenguajes. ¡Pylearn es un gran doctor! 🌡️",
    "correctAnswer": "Fiebre leve",
    "orderIndex": 91,
    "coins": 12,
    "xp": 20,
    "theme": "🌡️ Detector de fiebre del doctor Pylearn",
    "pytoReaction": "¡Diagnóstico: fiebre leve! Pylearn receta 2 litros de agua 🐍🌡️"
  },
  {
    "id": 92,
    "title": "Variables: Walrus operator",
    "description": "¿Qué imprime el detector de spam con walrus operator?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "predict_output",
    "question": "mensaje = \"Gana dinero rápido haciendo nada!!!\"\nif (n := len(mensaje)) > 20:\n    print(f\"Mensaje largo: {n} caracteres\")",
    "options": [
      "Mensaje largo: True caracteres",
      "Mensaje largo: 35 caracteres",
      "Mensaje largo: 39 caracteres",
      "Error: := no es un operador válido"
    ],
    "hint": "Pista: Revisa los conceptos de Walrus operator.",
    "explanation": "El walrus operator := (Python 3.8+) asigna y evalúa en la misma expresión. n := len(mensaje) guarda el largo en n Y lo compara con 20. 'Gana dinero rápido haciendo nada!!!' tiene 35 caracteres. ¡Una línea, dos operaciones! 🎯",
    "correctAnswer": "Mensaje largo: 35 caracteres",
    "orderIndex": 92,
    "coins": 12,
    "xp": 20,
    "theme": "🎯 Detector de spam eficiente",
    "pytoReaction": "¡40 chars de spam detectados! Pylearn usa Python 3.8 como pro 🐍🎯"
  },
  {
    "id": 93,
    "title": "Variables: Operador ternario",
    "description": "¿Cuál es el resultado del operador ternario del actor Pylearn?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "multiple_choice",
    "question": "audiencia = 5000\npremio = \"Oscar\" if audiencia > 1000 else \"Sin premio\"\nprint(premio)",
    "options": [
      "Sin premio",
      "Oscar",
      "True",
      "5000"
    ],
    "hint": "Pista: Revisa los conceptos de Operador ternario.",
    "explanation": "valor_si_true if condicion else valor_si_false es el operador ternario de Python. 5000 > 1000 es True → premio = 'Oscar'. Es una línea equivalente a if/else de 4 líneas. ¡Pylearn gana el Oscar! 🎭",
    "correctAnswer": "Oscar",
    "orderIndex": 93,
    "coins": 12,
    "xp": 20,
    "theme": "🎭 Decisión dramática de Pylearn",
    "pytoReaction": "¡Y el Oscar es para... PYTO! El actor más pythónico 🐍🎭"
  },
  {
    "id": 94,
    "title": "Variables: División entera y módulo",
    "description": "Pylearn reparte pizza entre sus amigos. ¿Cuántas porciones sobran?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "predict_output",
    "question": "porciones = 17\namigos = 5\nsobra = porciones % amigos\nenteras = porciones // amigos\nprint(f\"Cada uno: {enteras}, sobran: {sobra}\")",
    "options": [
      "Cada uno: 3, sobran: 2",
      "Cada uno: 3.4, sobran: 2",
      "Cada uno: 4, sobran: 1",
      "Cada uno: 3, sobran: 1"
    ],
    "hint": "Pista: Revisa los conceptos de División entera y módulo.",
    "explanation": "// es división entera (sin decimales): 17//5 = 3. % es módulo (resto): 17%5 = 2 (5*3=15, sobran 2). Ambos operadores son esenciales en programación. ¡3 porciones cada uno y 2 sobran! 🍕",
    "correctAnswer": "Cada uno: 3, sobran: 2",
    "orderIndex": 94,
    "coins": 12,
    "xp": 20,
    "theme": "🍕 Repartiendo pizza equitativamente",
    "pytoReaction": "¡Pylearn se come las 2 porciones sobrantes! Privilegio del admin 🐍🍕"
  },
  {
    "id": 95,
    "title": "Variables: Referencia vs copia",
    "description": "Pylearn clona su personaje pero ambos reciben el daño. ¿Por qué?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "advanced",
    "type": "bug",
    "question": "original = {\"vida\": 100, \"nivel\": 50}\nclon = original\nclon[\"vida\"] = 0\nprint(original[\"vida\"])",
    "options": [
      "100 — el original no fue tocado",
      "0 — ambos apuntan al mismo dict",
      "50 — tomó el nivel",
      "Error: no puedes modificar un clon"
    ],
    "hint": "Pista: Revisa los conceptos de Referencia vs copia.",
    "explanation": "clon = original NO crea una copia — ambas variables apuntan al MISMO objeto dict en memoria. Modificar clon modifica original. Fix: clon = original.copy() (copia superficial) o copy.deepcopy(original) para anidados. ¡El bug del clon! 👾",
    "correctAnswer": "0 — ambos apuntan al mismo dict",
    "orderIndex": 95,
    "coins": 25,
    "xp": 35,
    "theme": "👾 El clon bugueado del personaje",
    "pytoReaction": "¡Bug del clon! Pylearn aprende la diferencia entre referencia y copia 🐍👾"
  },
  {
    "id": 96,
    "title": "Variables: Global vs local",
    "description": "¿Qué imprime el monitor climático de Pylearn?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "advanced",
    "type": "predict_output",
    "question": "temperatura = 25\n\ndef medir_local():\n    temperatura = 40\n    print(f\"Local: {temperatura}\")\n\nmedir_local()\nprint(f\"Global: {temperatura}\")",
    "options": [
      "Local: 40\\nGlobal: 40",
      "Local: 25\\nGlobal: 25",
      "Local: 40\\nGlobal: 25",
      "Error: nombre duplicado de variable"
    ],
    "hint": "Pista: Revisa los conceptos de Global vs local.",
    "explanation": "La temperatura=40 dentro de medir_local() es una variable LOCAL — no modifica la global. Son dos variables diferentes con el mismo nombre en scopes distintos. Para modificar la global: usar 'global temperatura' dentro de la función. 🌍",
    "correctAnswer": "Local: 40\nGlobal: 25",
    "orderIndex": 96,
    "coins": 25,
    "xp": 35,
    "theme": "🌍 Temperatura global vs local del planeta",
    "pytoReaction": "¡Scopes dominados! El planeta de Pylearn sigue a 25° 🐍🌍"
  },
  {
    "id": 97,
    "title": "Variables: is vs ==",
    "description": "¿Qué imprime el comparador de identidad del bot de Pylearn?",
    "topic": "Variables básicas - Misión 2",
    "difficulty": "advanced",
    "type": "multiple_choice",
    "question": "a = [1, 2, 3]\nb = [1, 2, 3]\nc = a\nprint(a == b)\nprint(a is b)\nprint(a is c)",
    "options": [
      "True\\nTrue\\nTrue",
      "True\\nFalse\\nTrue",
      "False\\nFalse\\nTrue",
      "True\\nFalse\\nFalse"
    ],
    "hint": "Pista: Revisa los conceptos de is vs ==.",
    "explanation": "== compara VALORES (a y b tienen los mismos números → True). 'is' compara IDENTIDAD en memoria (a y b son objetos distintos → False). c = a hace que c apunte al MISMO objeto que a → a is c = True. ¡is vs == es un concepto fundamental! 🤖",
    "correctAnswer": "True\\nFalse\\nTrue",
    "orderIndex": 97,
    "coins": 25,
    "xp": 35,
    "theme": "🤖 Comparador de identidad del bot",
    "pytoReaction": "¡is vs ==! Pylearn ya nunca confunde identidad con igualdad 🐍🤖"
  }
];

