import type { ExerciseData } from "../types";

export const topicExercises: ExerciseData[] = [
  {
    "id": 98,
    "title": "Strings: len()",
    "description": "Tu ex te mandó un párrafo completo a las 2am. ¿Cómo contas cuántos caracteres tiene el mensaje?",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "mensaje = \"oye creo que deberíamos hablar...\"",
    "options": [
      "mensaje.length",
      "length(mensaje)",
      "len(mensaje)",
      "mensaje.size()"
    ],
    "hint": "Pista: Revisa los conceptos de len().",
    "explanation": "len() es la función universal de Python para medir longitud. No existe .length ni .size() como en JavaScript. ¡Con len() sabes qué tan largo es el drama! 📏",
    "correctAnswer": "len(mensaje)",
    "orderIndex": 98,
    "coins": 5,
    "xp": 10,
    "theme": "💌 Mensaje de tu ex",
    "pytoReaction": "¡Correcto! Pylearn también midió el mensaje con len() 🐍😅"
  },
  {
    "id": 99,
    "title": "Strings: len()",
    "description": "¿Cuántos caracteres tiene el nombre del artista?",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "artista = \"Bad Bunny\"\nprint(len(artista))",
    "options": [
      "7",
      "8",
      "9",
      "10"
    ],
    "hint": "Pista: Revisa los conceptos de len().",
    "explanation": "B-a-d- -B-u-n-n-y = 9 caracteres. ¡El espacio también cuenta! len() no discrimina, cuenta absolutamente todo lo que está dentro de las comillas 🎵",
    "correctAnswer": "9",
    "orderIndex": 99,
    "coins": 5,
    "xp": 10,
    "theme": "🎵 Nombre de artista",
    "pytoReaction": "¡Exacto! Pylearn es fan de Bad Bunny 🐍🎵"
  },
  {
    "id": 100,
    "title": "Strings: Métodos de string",
    "description": "Pylearn está enojado y convierte su queja a MAYÚSCULAS para que lo escuchen:",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "queja = \"esto es inaceptable señor gerente\"\nprint(queja.___)",
    "options": [
      "upper()",
      "UPPER()",
      "toUpper()",
      "mayusculas()",
      "caps()",
      "Upper()"
    ],
    "hint": "Pista: Revisa los conceptos de Métodos de string.",
    "explanation": ".upper() convierte todo a MAYÚSCULAS. .lower() hace lo contrario. Son métodos propios del string, van después del punto. ¡Karen mode: ON! 😤",
    "correctAnswer": "upper()",
    "orderIndex": 100,
    "coins": 5,
    "xp": 10,
    "theme": "😤 Modo Karen activado",
    "pytoReaction": "¡CORRECTO! PYTO ESTÁ MUY ORGULLOSO 🐍"
  },
  {
    "id": 101,
    "title": "Strings: .replace()",
    "description": "El editor reemplaza el nombre del personaje en el guión. ¿Cuál es el método correcto?",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "guion = \"Heisenberg cocina en el desierto\"\nnuevo = guion._____(\"Heisenberg\", \"Walter White\")\nprint(nuevo)",
    "options": [
      "swap(\"Heisenberg\", \"Walter White\")",
      "replace(\"Heisenberg\", \"Walter White\")",
      "change(\"Heisenberg\", \"Walter White\")",
      "sub(\"Heisenberg\", \"Walter White\")"
    ],
    "hint": "Pista: Revisa los conceptos de .replace().",
    "explanation": ".replace(viejo, nuevo) reemplaza TODAS las ocurrencias del texto viejo por el nuevo. No modifica el string original — retorna uno nuevo. ¡Say my name! 🎬",
    "correctAnswer": "replace(\"Heisenberg\", \"Walter White\")",
    "orderIndex": 101,
    "coins": 5,
    "xp": 10,
    "theme": "🎬 Breaking Bad — editar guión",
    "pytoReaction": "¡I am the one who codes! Pylearn conoce .replace() 🐍"
  },
  {
    "id": 102,
    "title": "Strings: .replace()",
    "description": "El chef corrige un error en la receta. ¿Qué imprime?",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "receta = \"Agrega sal, sal y más sal\"\ncorregida = receta.replace(\"sal\", \"miso\")\nprint(corregida)",
    "options": [
      "Agrega miso, sal y más sal",
      "Agrega miso, miso y más miso",
      "Agrega sal, miso y más sal",
      "Agrega sal, sal y más miso"
    ],
    "hint": "Pista: Revisa los conceptos de .replace().",
    "explanation": ".replace() reemplaza TODAS las ocurrencias, no solo la primera. 'sal' aparece 3 veces → las 3 se convierten en 'miso'. Si solo quieres reemplazar n veces: .replace('sal', 'miso', 1) 🍜",
    "correctAnswer": "Agrega miso, miso y más miso",
    "orderIndex": 102,
    "coins": 5,
    "xp": 10,
    "theme": "🍜 Corrector de receta de ramen",
    "pytoReaction": "¡Ramen de miso perfecto! Pylearn es el chef del año 🐍🍜"
  },
  {
    "id": 103,
    "title": "Strings: .split()",
    "description": "Pylearn divide el setlist separado por comas en una lista de canciones:",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "setlist = \"Bohemian Rhapsody,Stairway to Heaven,Smells Like Teen Spirit\"\ncanciones = setlist.___(\",\")\nprint(canciones)",
    "options": [
      "split",
      "divide",
      "separate",
      "cut",
      "slice",
      "explode"
    ],
    "hint": "Pista: Revisa los conceptos de .split().",
    "explanation": ".split(separador) divide un string en una lista usando el separador indicado. Sin argumento divide por espacios. Es el opuesto de .join(). ¡El setlist de Pylearn ya es una lista! 🎸",
    "correctAnswer": "split",
    "orderIndex": 103,
    "coins": 5,
    "xp": 10,
    "theme": "🎸 Setlist del concierto de Rock",
    "pytoReaction": "¡3 canciones épicas en lista! Pylearn toca todas 🐍🎸"
  },
  {
    "id": 104,
    "title": "Strings: .split()",
    "description": "¿Cuántos nakamas tiene Luffy según el split?",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "tripulacion = \"Luffy Zoro Nami Usopp Sanji\"\nmiembros = tripulacion.split()\nprint(len(miembros))",
    "options": [
      "4",
      "5",
      "24",
      "1"
    ],
    "hint": "Pista: Revisa los conceptos de .split().",
    "explanation": ".split() sin argumentos divide por ESPACIOS. 5 nombres separados por espacios = lista de 5 elementos. len() cuenta los elementos. ¡Luffy tiene 5 nakamas! ⚓",
    "correctAnswer": "5",
    "orderIndex": 104,
    "coins": 5,
    "xp": 10,
    "theme": "🌊 One Piece — tripulación de Luffy",
    "pytoReaction": "¡5 nakamas! Pylearn quiere ser el Rey de los Piratas Pythoneros 🐍⚓"
  },
  {
    "id": 105,
    "title": "Strings: .join()",
    "description": "Pylearn une los nombres de los pingüinos con ' - ' entre cada uno. ¿Cuál es la sintaxis correcta?",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "pinguinos = [\"Tux\", \"Skipper\", \"Pingu\"]\nresultado = ___.join(pinguinos)",
    "options": [
      "pinguinos.join(\" - \")",
      "\" - \".join(pinguinos)",
      "join(pinguinos, \" - \")",
      "\"-\".join(\" - \", pinguinos)"
    ],
    "hint": "Pista: Revisa los conceptos de .join().",
    "explanation": ".join() se llama sobre el SEPARADOR, no sobre la lista. Sintaxis: separador.join(lista). Produce: 'Tux - Skipper - Pingu'. Es el opuesto de .split(). ¡Los pingüinos marchan en formación! 🐧",
    "correctAnswer": "\" - \".join(pinguinos)",
    "orderIndex": 105,
    "coins": 5,
    "xp": 10,
    "theme": "🐧 Pingüinos marchando",
    "pytoReaction": "¡Tux - Skipper - Pingu! Pylearn ama los pingüinos (¡y Linux!) 🐍🐧"
  },
  {
    "id": 106,
    "title": "Strings: .join()",
    "description": "¿Cuál es la contraseña del castillo de Pylearn?",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "partes = [\"rey\", \"dragon\", \"espada\"]\ncontra = \"_\".join(partes)\nprint(contra)",
    "options": [
      "rey dragon espada",
      "rey_dragon_espada",
      "[rey, dragon, espada]",
      "reydragonesp ada"
    ],
    "hint": "Pista: Revisa los conceptos de .join().",
    "explanation": "\"_\".join([...]) une todos los elementos de la lista con _ entre cada uno. Muy útil para crear slugs, contraseñas o paths. ¡La contraseña del castillo está segura! 🏰",
    "correctAnswer": "rey_dragon_espada",
    "orderIndex": 106,
    "coins": 5,
    "xp": 10,
    "theme": "🏰 Contraseña medieval",
    "pytoReaction": "¡Contraseña creada! El castillo de Pylearn es impenetrable 🐍🏰"
  },
  {
    "id": 107,
    "title": "Strings: .split() y .join()",
    "description": "Los créditos del musical tienen un error. ¿Cuál línea está mal?",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "bug",
    "question": "actores = [\"Lin\", \"Miranda\", \"Renée\"]\ncreditos = actores.join(\", \")\nprint(creditos)",
    "options": [
      "actores no es una lista válida",
      "actores.join() está al revés — debería ser \", \".join(actores)",
      "join necesita más de 3 elementos",
      "Las comillas del separador están mal"
    ],
    "hint": "Pista: Revisa los conceptos de .split() y .join().",
    "explanation": ".join() pertenece al SEPARADOR (el string), no a la lista. Correcto: \", \".join(actores). Si llamas actores.join() → AttributeError: list has no attribute 'join'. ¡Los créditos de Broadway arreglados! 🎭",
    "correctAnswer": "actores.join() está al revés — debería ser \", \".join(actores)",
    "orderIndex": 107,
    "coins": 5,
    "xp": 10,
    "theme": "🎭 Broadway — error en los créditos",
    "pytoReaction": "¡Standing ovation para el debugger Pylearn! 🐍👏"
  },
  {
    "id": 108,
    "title": "Strings: .count()",
    "description": "El guardabosques cuenta cuántos leones menciona el reporte. ¿Qué retorna?",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "reporte = \"Avistamos un leon cerca del leon alfa y otro leon joven\"\nprint(reporte.count(\"leon\"))",
    "options": [
      "2",
      "3",
      "4",
      "1"
    ],
    "hint": "Pista: Revisa los conceptos de .count().",
    "explanation": ".count(sub) cuenta cuántas veces aparece el substring. 'leon' aparece 3 veces. Es case-sensitive: 'leon' ≠ 'Leon'. ¡Hay 3 leones en el safari! 🦁",
    "correctAnswer": "3",
    "orderIndex": 108,
    "coins": 5,
    "xp": 10,
    "theme": "🦁 Safari — contando leones",
    "pytoReaction": "¡3 leones! Pylearn los cuenta sin moverse del jeep 🐍🦁"
  },
  {
    "id": 109,
    "title": "Strings: .startswith() / .endswith()",
    "description": "Pylearn verifica que el archivo sea una imagen PNG:",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "archivo = \"foto_pyto.png\"\nes_imagen = archivo.___(\"png\")\nprint(es_imagen)  # → True",
    "options": [
      "endswith",
      "startswith",
      "contains",
      "ends_with",
      "ends",
      "finish"
    ],
    "hint": "Pista: Revisa los conceptos de .startswith() / .endswith().",
    "explanation": ".endswith(sufijo) verifica si el string termina con ese texto. .startswith(prefijo) verifica el inicio. Ambos retornan True/False. ¡Perfecto para validar extensiones de archivos! 📁",
    "correctAnswer": "endswith",
    "orderIndex": 109,
    "coins": 5,
    "xp": 10,
    "theme": "📁 Validador de archivos de Pylearn",
    "pytoReaction": "¡archivo.png validado! Pylearn es el mejor DevOps 🐍📁"
  },
  {
    "id": 110,
    "title": "Strings: .find()",
    "description": "¿En qué posición encuentra Pylearn la pista clave?",
    "topic": "Strings básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "evidencia = \"el sospechoso usa sombrero negro\"\nposicion = evidencia.find(\"sombrero\")\nprint(posicion)",
    "options": [
      "17",
      "18",
      "19",
      "-1"
    ],
    "hint": "Pista: Revisa los conceptos de .find().",
    "explanation": ".find(sub) retorna el índice donde EMPIEZA el substring. 'e'=0,'l'=1,' '=2,'s'=3... contando hasta 's' de 'sombrero' = índice 18. Si no existe retorna -1. ¡Pylearn encontró la pista! 🔍",
    "correctAnswer": "18",
    "orderIndex": 110,
    "coins": 5,
    "xp": 10,
    "theme": "🔍 Investigador Pylearn buscando pista",
    "pytoReaction": "¡Caso resuelto! Pylearn Poirot al servicio 🐍🕵️"
  }
];

