import type { ExerciseData } from "../types";

export const topicExercises: ExerciseData[] = [
  {
    "id": 111,
    "title": "Strings: Multiplicación de strings",
    "description": "¿Cómo crea Pylearn una fila de 5 pastelitos de texto?",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "¿Cómo crea Pylearn una fila de 5 pastelitos de texto?",
    "options": [
      "\"🧁\" + 5",
      "\"🧁\" * 5",
      "repeat(\"🧁\", 5)",
      "\"🧁\".times(5)"
    ],
    "hint": "Pista: Revisa los conceptos de Multiplicación de strings.",
    "explanation": "Los strings se pueden multiplicar con *. \"abc\" * 3 = \"abcabcabc\". Muy útil para crear separadores, barras de progreso de texto, bordes decorativos, etc. 🎉",
    "correctAnswer": "\"🧁\" * 5",
    "orderIndex": 111,
    "coins": 5,
    "xp": 10,
    "theme": "🎉 Fiesta de cumpleaños de Pylearn",
    "pytoReaction": "🧁🧁🧁🧁🧁 ¡Feliz cumpleaños Pylearn! 🐍🎂"
  },
  {
    "id": 112,
    "title": "Strings: .strip() avanzado",
    "description": "Pylearn limpia los datos sucios del CSV que vienen con espacios y saltos de línea:",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "dato_sucio = \"   python\\n\"\ndato_limpio = dato_sucio.___()\nprint(dato_limpio)  # → 'python'",
    "options": [
      "strip",
      "clean",
      "trim",
      "lstrip",
      "rstrip",
      "clear"
    ],
    "hint": "Pista: Revisa los conceptos de .strip() avanzado.",
    "explanation": ".strip() elimina espacios, tabs (\\t) y saltos de línea (\\n) del inicio y fin. .lstrip() solo izquierda, .rstrip() solo derecha. ¡Los datos de Pylearn quedaron impecables! 📊",
    "correctAnswer": "strip",
    "orderIndex": 112,
    "coins": 5,
    "xp": 10,
    "theme": "📊 Limpiando datos del CSV",
    "pytoReaction": "¡Datos limpios! Pylearn es el rey del data cleaning 🐍📊"
  },
  {
    "id": 113,
    "title": "Strings: Encadenamiento de métodos",
    "description": "¿Qué imprime el normalizador de input del chatbot de Pylearn?",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "entrada = \"  HOLA MUNDO  \"\nnormal = entrada.strip().lower().replace(\"mundo\", \"python\")\nprint(normal)",
    "options": [
      "HOLA MUNDO",
      "hola mundo",
      "hola python",
      "  hola python  "
    ],
    "hint": "Pista: Revisa los conceptos de Encadenamiento de métodos.",
    "explanation": "Los métodos se encadenan de izquierda a derecha. strip() quita espacios → 'HOLA MUNDO'. lower() → 'hola mundo'. replace() → 'hola python'. ¡El chatbot de Pylearn entiende todo! 🤖",
    "correctAnswer": "hola python",
    "orderIndex": 113,
    "coins": 5,
    "xp": 10,
    "theme": "🤖 Normalizando entrada de usuario",
    "pytoReaction": "¡Input normalizado! El chatbot de Pylearn es profesional 🐍🤖"
  },
  {
    "id": 114,
    "title": "Strings: Slicing",
    "description": "Netflix recorta el título para que quepa en la tarjeta. ¿Qué aparece?",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "predict_output",
    "question": "titulo = \"Stranger Things\"\nprint(titulo[0:8])",
    "options": [
      "Stranger",
      "Stranger ",
      "Strange",
      "trangerT"
    ],
    "hint": "Pista: Revisa los conceptos de Slicing.",
    "explanation": "S=0,t=1,r=2,a=3,n=4,g=5,e=6,r=7, =8. [0:8] toma del índice 0 al 7 (el 8 NO se incluye). Eso es 'Stranger ' con espacio al final. ¡Los índices empiezan en 0! 🎬",
    "correctAnswer": "Stranger ",
    "orderIndex": 114,
    "coins": 12,
    "xp": 20,
    "theme": "🎬 Netflix truncado",
    "pytoReaction": "¡Bien! Pylearn vio Stranger Things 4 veces 🐍📺"
  },
  {
    "id": 115,
    "title": "Strings: f-strings",
    "description": "¿Cuál f-string muestra correctamente el perfil del jugador?",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "multiple_choice",
    "question": "usuario = \"PylearnGod\"\nrank = \"Diamante\"\npuntos = 9500",
    "options": [
      "f\"Usuario: usuario | Rank: rank\"",
      "f\"Usuario: {usuario} | Rank: {rank} | {puntos} pts\"",
      "\"Usuario: \" + usuario + \" | Rank: \" + rank",
      "f\"Usuario: [usuario] | Rank: [rank]\""
    ],
    "hint": "Pista: Revisa los conceptos de f-strings.",
    "explanation": "f-strings usan {} para insertar variables. La 'f' va ANTES de las comillas. No confundir con [] (eso es para listas) ni sin llaves (eso imprime el texto literal). ¡El perfil queda épico! 🎮",
    "correctAnswer": "f\"Usuario: {usuario} | Rank: {rank} | {puntos} pts\"",
    "orderIndex": 115,
    "coins": 12,
    "xp": 20,
    "theme": "🎮 Perfil Gamer Pro",
    "pytoReaction": "¡GG! Pylearn también llegó a Diamante 🐍💎"
  },
  {
    "id": 116,
    "title": "Strings: Concatenación",
    "description": "El entrenador Pylearn intenta mostrar su Pokémon pero hay un error. ¿Cuál es?",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "bug",
    "question": "pokemon = \"Charizard\"\nnivel = 100\nprint(\"Mi \" + pokemon + \" nivel \" + nivel)",
    "options": [
      "pokemon necesita ir sin comillas",
      "No se puede concatenar str + int con +",
      "print() no acepta múltiples strings",
      "nivel debe ir antes que pokemon"
    ],
    "hint": "Pista: Revisa los conceptos de Concatenación.",
    "explanation": "Python no mezcla strings e ints con +. Soluciones: str(nivel) para convertir, o mejor aún usar f-string: f\"Mi {pokemon} nivel {nivel}\". ¡Charizard merece mejor código! 🐉",
    "correctAnswer": "No se puede concatenar str + int con +",
    "orderIndex": 116,
    "coins": 12,
    "xp": 20,
    "theme": "🐉 Pokémon GO",
    "pytoReaction": "¡Bien detectado! Pylearn usa f-strings como pro 🐍🔥"
  },
  {
    "id": 117,
    "title": "Strings: Slicing avanzado",
    "description": "¿Qué extrae Pylearn del log de error del servidor?",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "multiple_choice",
    "question": "log = \"2024-01-15 ERROR: conexión fallida\"\nfecha = log[:10]\nerror = log[11:16]\nprint(f\"{fecha} | {error}\")",
    "options": [
      "2024-01-15 | ERROR",
      "2024-01 | ERROR:",
      "2024-01-15 | ERROR:",
      "2024-01-1 | ERROR"
    ],
    "hint": "Pista: Revisa los conceptos de Slicing avanzado.",
    "explanation": "log[:10] toma índices 0-9 = '2024-01-15'. log[11:16] toma índices 11-15 = 'ERROR'. El espacio está en índice 10. Slicing preciso es esencial para parsear logs y datos. 🤖",
    "correctAnswer": "2024-01-15 | ERROR",
    "orderIndex": 117,
    "coins": 12,
    "xp": 20,
    "theme": "🤖 Extrayendo datos del log del servidor",
    "pytoReaction": "¡Log parseado! Pylearn es el mejor SysAdmin 🐍💻"
  },
  {
    "id": 118,
    "title": "Strings: .format()",
    "description": "¿Cuál es el output del generador de tickets de PyFest?",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "multiple_choice",
    "question": "ticket = \"Evento: {} | Asiento: {} | Precio: ${:.2f}\"\nprint(ticket.format(\"PyFest 2024\", \"A-14\", 29.5))",
    "options": [
      "Evento: PyFest 2024 | Asiento: A-14 | Precio: $29.5",
      "Evento: PyFest 2024 | Asiento: A-14 | Precio: $29.50",
      "Evento: {} | Asiento: {} | Precio: $29.50",
      "Error: .format() necesita nombres en las llaves"
    ],
    "hint": "Pista: Revisa los conceptos de .format().",
    "explanation": ".format() llena las {} en orden. {:.2f} es un especificador de formato: 2 decimales fijos. 29.5 → 29.50. Los f-strings son más modernos pero .format() sigue siendo útil con plantillas. 🎟️",
    "correctAnswer": "Evento: PyFest 2024 | Asiento: A-14 | Precio: $29.50",
    "orderIndex": 118,
    "coins": 12,
    "xp": 20,
    "theme": "🎟️ Generador de tickets de evento",
    "pytoReaction": "¡Ticket generado para PyFest 2024! Pylearn tiene el A-14 🐍🎟️"
  },
  {
    "id": 119,
    "title": "Strings: Multiline strings",
    "description": "Pylearn crea un mensaje de múltiples líneas sin usar \\n explícito:",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "fill_blank",
    "question": "pergamino = ___\nEstimado Pylearn,\nEres aceptado en Hogwarts.\nDept. de Admisiones\n___\nprint(pergamino)",
    "options": [
      "\"\"\"",
      "'''",
      "\"\"",
      "```",
      "''",
      "##"
    ],
    "hint": "Pista: Revisa los conceptos de Multiline strings.",
    "explanation": "Las triple comillas \"\"\" o ''' crean strings de múltiples líneas. Los saltos de línea se incluyen literalmente. Útil para textos largos, HTML templates, SQL queries y docstrings. ¡El pergamino de Hogwarts tiene buen formato! 📜",
    "correctAnswer": "\"\"\"",
    "orderIndex": 119,
    "coins": 12,
    "xp": 20,
    "theme": "📜 Pergamino de Hogwarts",
    "pytoReaction": "¡Aceptado en Hogwarts! Pylearn aprende magia y Python 🐍🧙"
  },
  {
    "id": 120,
    "title": "Strings: Métodos de string",
    "description": "¿Qué imprime el detector de spam de Pylearn?",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "advanced",
    "type": "multiple_choice",
    "question": "email = \"   COMPRA AHORA!!!   \"\nclean = email.strip().lower()\nprint(clean)",
    "options": [
      "COMPRA AHORA!!!",
      "compra ahora!!!",
      "   compra ahora!!!   ",
      "compra ahora"
    ],
    "hint": "Pista: Revisa los conceptos de Métodos de string.",
    "explanation": ".strip() elimina espacios al inicio y al final. .lower() convierte a minúsculas. Se pueden encadenar métodos. El resultado es 'compra ahora!!!' sin espacios y en minúsculas 🕵️",
    "correctAnswer": "compra ahora!!!",
    "orderIndex": 120,
    "coins": 25,
    "xp": 35,
    "theme": "🕵️ Detector de spam",
    "pytoReaction": "¡Spam detectado y neutralizado! Pylearn te protege 🐍🛡️"
  },
  {
    "id": 121,
    "title": "Strings: Slicing",
    "description": "Pylearn invierte su nombre para crear su alias hacker:",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "advanced",
    "type": "fill_blank",
    "question": "nombre = \"Pylearn\"\nalias = nombre[___]\nprint(alias)  # → otyp",
    "options": [
      "::-1",
      "-1:",
      "::1",
      "::-2",
      "reverse()",
      "0:-1"
    ],
    "hint": "Pista: Revisa los conceptos de Slicing.",
    "explanation": "[::-1] es el slicing mágico de Python para invertir. Significa: desde el inicio hasta el final, de 1 en 1 hacia atrás. ¡La navaja suiza de los strings! 🌀",
    "correctAnswer": "::-1",
    "orderIndex": 121,
    "coins": 25,
    "xp": 35,
    "theme": "🌀 String invertido",
    "pytoReaction": "¡otyp nació! El hacker más verde del mundo 🐍💻"
  },
  {
    "id": 122,
    "title": "Strings: Regex básico con re",
    "description": "¿Cuántos emails encuentra el extractor de Pylearn?",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "advanced",
    "type": "predict_output",
    "question": "import re\nlog = \"Contactos: pyto@snake.py, admin@pylearn.com, noreply@test.io\"\nemails = re.findall(r'[\\w.]+@[\\w.]+', log)\nprint(len(emails))",
    "options": [
      "1",
      "2",
      "3",
      "0"
    ],
    "hint": "Pista: Revisa los conceptos de Regex básico con re.",
    "explanation": "re.findall(patrón, texto) retorna todas las coincidencias como lista. El patrón [\\w.]+@[\\w.]+ busca: uno o más (word chars o puntos), @, uno o más (word chars o puntos). Encuentra los 3 emails. ¡El extractor funciona! 🔍",
    "correctAnswer": "3",
    "orderIndex": 122,
    "coins": 25,
    "xp": 35,
    "theme": "🔍 Extractor de emails del log",
    "pytoReaction": "¡3 emails encontrados! Pylearn domina las regex 🐍🔍"
  },
  {
    "id": 123,
    "title": "Strings: String format avanzado",
    "description": "¿Qué imprime el dashboard de métricas de Pylearn?",
    "topic": "Strings básicas - Misión 2",
    "difficulty": "advanced",
    "type": "predict_output",
    "question": "usuarios = 15420\nprecision = 0.8734\nprint(f\"Usuarios: {usuarios:,}\")\nprint(f\"Precisión: {precision:.1%}\")",
    "options": [
      "Usuarios: 15420\\nPrecisión: 0.8734",
      "Usuarios: 15,420\\nPrecisión: 87.3%",
      "Usuarios: 15.420\\nPrecisión: 87.34%",
      "Usuarios: 15,420\\nPrecisión: 0.87%"
    ],
    "hint": "Pista: Revisa los conceptos de String format avanzado.",
    "explanation": "{:,} formatea números con separador de miles. {:.1%} convierte a porcentaje con 1 decimal (multiplica por 100 automáticamente). 0.8734 × 100 = 87.34 → .1% → 87.3%. ¡Dashboards profesionales con f-strings! 📊",
    "correctAnswer": "Usuarios: 15,420\nPrecisión: 87.3%",
    "orderIndex": 123,
    "coins": 25,
    "xp": 35,
    "theme": "📊 Dashboard de métricas de Pylearn",
    "pytoReaction": "¡15,420 usuarios y 87.3% de precisión! Pylearn está despegando 🐍📊"
  }
];

