import type { ExerciseData } from "../types";

export const topicExercises: ExerciseData[] = [
  {
    "id": 124,
    "title": "Listas: Crear listas",
    "description": "Pylearn quiere guardar su inventario de Minecraft. ¿Cuál es la sintaxis correcta?",
    "topic": "Listas básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "Pylearn quiere guardar su inventario de Minecraft. ¿Cuál es la sintaxis correcta?",
    "options": [
      "inventario = (\"espada\", \"pico\", \"antorcha\")",
      "inventario = [\"espada\", \"pico\", \"antorcha\"]",
      "inventario = {\"espada\", \"pico\", \"antorcha\"}",
      "inventario = <\"espada\", \"pico\", \"antorcha\">"
    ],
    "hint": "Pista: Revisa los conceptos de Crear listas.",
    "explanation": "Las listas usan corchetes []. Los () son para tuplas (inmutables) y los {} son para sets o diccionarios. Las listas son el inventario más flexible de Python 🎮",
    "correctAnswer": "inventario = [\"espada\", \"pico\", \"antorcha\"]",
    "orderIndex": 124,
    "coins": 5,
    "xp": 10,
    "theme": "🎮 Inventario Minecraft",
    "pytoReaction": "¡Inventario guardado! Ahora a minar diamantes 🐍⛏️"
  },
  {
    "id": 125,
    "title": "Listas: Acceso por índice",
    "description": "¿Quién quedó en PRIMER lugar del torneo?",
    "topic": "Listas básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "podio = [\"PylearnGod\", \"AnaKiller\", \"LuisNoob\"]\nprint(podio[0])",
    "options": [
      "AnaKiller",
      "PylearnGod",
      "LuisNoob",
      "1"
    ],
    "hint": "Pista: Revisa los conceptos de Acceso por índice.",
    "explanation": "¡Los índices en Python empiezan en 0! podio[0] es el primero, podio[1] el segundo y podio[2] el tercero. ¡PylearnGod ganó el torneo! 🏆",
    "correctAnswer": "PylearnGod",
    "orderIndex": 125,
    "coins": 5,
    "xp": 10,
    "theme": "🏆 Podio del torneo",
    "pytoReaction": "¡Claro que Pylearn ganó! Era predecible 🐍🥇"
  },
  {
    "id": 126,
    "title": "Listas: append()",
    "description": "Pylearn agrega un nuevo producto al carrito:",
    "topic": "Listas básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "carrito = [\"laptop\", \"mouse\"]\ncarrito.___(\"teclado mecánico\")\nprint(carrito)",
    "options": [
      "append",
      "add",
      "push",
      "insert",
      "agregar",
      "extend"
    ],
    "hint": "Pista: Revisa los conceptos de append().",
    "explanation": ".append() agrega un elemento AL FINAL de la lista. .insert(i, x) agrega en una posición específica. .add() no existe en listas (es para sets). ¡Carrito actualizado! 🛒",
    "correctAnswer": "append",
    "orderIndex": 126,
    "coins": 5,
    "xp": 10,
    "theme": "🛒 Carrito de compras",
    "pytoReaction": "¡Teclado mecánico en el carrito! Pylearn tiene buen gusto 🐍⌨️"
  },
  {
    "id": 127,
    "title": "Listas: Acceso por índice",
    "description": "¡Queda solo una pizza y todos la quieren! ¿Cómo accedes al ÚLTIMO elemento sin saber cuántos hay?",
    "topic": "Listas básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "pedidos = [\"hawaiana\", \"pepperoni\", \"4 quesos\", \"bbq\"]",
    "options": [
      "pedidos[4]",
      "pedidos[last]",
      "pedidos[-1]",
      "pedidos.last()"
    ],
    "hint": "Pista: Revisa los conceptos de Acceso por índice.",
    "explanation": "El índice -1 siempre apunta al último elemento, -2 al penúltimo, etc. ¡Perfectamente útil cuando no sabes el tamaño de la lista! La pizza BBQ es tuya 🍕",
    "correctAnswer": "pedidos[-1]",
    "orderIndex": 127,
    "coins": 5,
    "xp": 10,
    "theme": "🍕 Última pizza",
    "pytoReaction": "¡La pizza BBQ es de Pylearn! Lo supo desde el principio 🐍🍕"
  },
  {
    "id": 128,
    "title": "Listas: append()",
    "description": "Pylearn intenta agregar una canción a su playlist pero algo falla. ¿Qué está mal?",
    "topic": "Listas básicas - Misión 1",
    "difficulty": "beginner",
    "type": "bug",
    "question": "playlist = [\"Bzrp Session 52\", \"Tití me preguntó\"]\nplaylist.append[\"La curiosidad\"]\nprint(playlist)",
    "options": [
      "playlist no es una lista válida",
      "Se usan [] en vez de () en append",
      "La canción necesita ir sin comillas",
      "append solo acepta números"
    ],
    "hint": "Pista: Revisa los conceptos de append().",
    "explanation": "Los métodos se llaman con PARÉNTESIS: playlist.append(\"La curiosidad\"). Los corchetes [] son para indexar (acceder a elementos). ¡Error clásico de principiante! 🎵",
    "correctAnswer": "Se usan [] en vez de () en append",
    "orderIndex": 128,
    "coins": 5,
    "xp": 10,
    "theme": "🎵 Playlist de Spotify",
    "pytoReaction": "¡Bug cazado! La playlist de Pylearn ya está completa 🐍🎵"
  },
  {
    "id": 129,
    "title": "Listas: .remove()",
    "description": "El admin Pylearn banea a un jugador tóxico del servidor. ¿Qué método elimina por valor?",
    "topic": "Listas básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "jugadores = [\"Pylearn\", \"AnaGamer\", \"ToxicNoob99\", \"LuisBot\"]\njugadores.___(\"ToxicNoob99\")",
    "options": [
      "delete(\"ToxicNoob99\")",
      "remove(\"ToxicNoob99\")",
      "pop(\"ToxicNoob99\")",
      "ban(\"ToxicNoob99\")"
    ],
    "hint": "Pista: Revisa los conceptos de .remove().",
    "explanation": ".remove(valor) elimina la PRIMERA ocurrencia del valor dado. Si no existe → ValueError. Si quieres eliminar por posición usa .pop(índice). ¡ToxicNoob99 baneado! 🔨",
    "correctAnswer": "remove(\"ToxicNoob99\")",
    "orderIndex": 129,
    "coins": 5,
    "xp": 10,
    "theme": "🎮 Banear jugador del servidor",
    "pytoReaction": "¡Ban aplicado! El servidor de Pylearn es zona libre de toxicidad 🐍🛡️"
  },
  {
    "id": 130,
    "title": "Listas: .remove()",
    "description": "Pylearn odia las aceitunas. ¿Qué queda en la pizza después de quitarlas?",
    "topic": "Listas básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "ingredientes = [\"queso\", \"aceitunas\", \"pepperoni\", \"aceitunas\"]\ningredientes.remove(\"aceitunas\")\nprint(ingredientes)",
    "options": [
      "[\"queso\", \"pepperoni\"]",
      "[\"queso\", \"pepperoni\", \"aceitunas\"]",
      "[\"queso\", \"aceitunas\", \"pepperoni\"]",
      "Error: aceitunas aparece dos veces"
    ],
    "hint": "Pista: Revisa los conceptos de .remove().",
    "explanation": ".remove() elimina solo la PRIMERA ocurrencia. La segunda 'aceitunas' sobrevive. Para eliminar todas: usa un while o list comprehension. ¡Pylearn todavía tiene una aceituna intrusa! 🍕",
    "correctAnswer": "[\"queso\", \"pepperoni\", \"aceitunas\"]",
    "orderIndex": 130,
    "coins": 5,
    "xp": 10,
    "theme": "🍕 Quitando ingrediente al gusto",
    "pytoReaction": "¡Una aceituna escapa! Pylearn la busca con un while loop 🐍🫒"
  },
  {
    "id": 131,
    "title": "Listas: .pop()",
    "description": "Pylearn saca la última carta del mazo y la guarda en su mano:",
    "topic": "Listas básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "mazo = [\"as\", \"rey\", \"reina\", \"joker\"]\ncarta = mazo.___()\nprint(carta)    # → joker\nprint(mazo)     # → [\"as\", \"rey\", \"reina\"]",
    "options": [
      "pop",
      "remove",
      "del",
      "extract",
      "take",
      "last"
    ],
    "hint": "Pista: Revisa los conceptos de .pop().",
    "explanation": ".pop() sin argumento elimina y RETORNA el último elemento. .pop(0) sacaría el primero. A diferencia de .remove(), .pop() retorna el valor eliminado para que puedas usarlo. ¡Pylearn sacó el joker! 🃏",
    "correctAnswer": "pop",
    "orderIndex": 131,
    "coins": 5,
    "xp": 10,
    "theme": "🃏 Sacando carta del mazo",
    "pytoReaction": "¡Joker en mano! Pylearn gana la partida 🐍🃏"
  },
  {
    "id": 132,
    "title": "Listas: .pop()",
    "description": "¿Qué satélite se lanza y cuál es la lista restante?",
    "topic": "Listas básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "satelites = [\"Explorer\", \"Sputnik\", \"Hubble\"]\nlanzado = satelites.pop(1)\nprint(lanzado)\nprint(satelites)",
    "options": [
      "Hubble\\n[\"Explorer\", \"Sputnik\"]",
      "Sputnik\\n[\"Explorer\", \"Hubble\"]",
      "Explorer\\n[\"Sputnik\", \"Hubble\"]",
      "Sputnik\\n[\"Explorer\", \"Sputnik\", \"Hubble\"]"
    ],
    "hint": "Pista: Revisa los conceptos de .pop().",
    "explanation": ".pop(1) elimina y retorna el elemento en índice 1 (Sputnik). La lista queda con Explorer e Hubble. ¡El Sputnik fue lanzado exitosamente al espacio! 🚀",
    "correctAnswer": "Sputnik\n[\"Explorer\", \"Hubble\"]",
    "orderIndex": 132,
    "coins": 5,
    "xp": 10,
    "theme": "🚀 Lanzando satélites al espacio",
    "pytoReaction": "¡Sputnik en órbita! Pylearn controla el centro espacial 🐍🚀"
  },
  {
    "id": 133,
    "title": "Listas: .sort()",
    "description": "¿Cuál es la diferencia clave entre sort() y sorted()?",
    "topic": "Listas básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "tiempos = [45, 12, 38, 7, 29]\ntiempos.sort()\nprint(tiempos)",
    "options": [
      "sort() retorna la lista ordenada, sorted() modifica en el lugar",
      "sort() modifica la lista en el lugar, sorted() retorna una nueva lista",
      "Son exactamente iguales",
      "sort() solo funciona con números"
    ],
    "hint": "Pista: Revisa los conceptos de .sort().",
    "explanation": ".sort() modifica la lista original y retorna None. sorted(lista) crea una NUEVA lista ordenada sin tocar la original. Si necesitas conservar el original: usa sorted(). ¡Los tiempos quedan: [7, 12, 29, 38, 45]! 🏆",
    "correctAnswer": "sort() modifica la lista en el lugar, sorted() retorna una nueva lista",
    "orderIndex": 133,
    "coins": 5,
    "xp": 10,
    "theme": "🏆 Podio del ranking de velocidad",
    "pytoReaction": "¡Pylearn en el lugar 1 con 7 segundos! 🐍🥇"
  },
  {
    "id": 134,
    "title": "Listas: .extend()",
    "description": "Pylearn fusiona dos menús de ramen en uno solo:",
    "topic": "Listas básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "menu1 = [\"shoyu\", \"miso\"]\nmenu2 = [\"tonkotsu\", \"shio\"]\nmenu1.___(menu2)\nprint(menu1)  # → ['shoyu', 'miso', 'tonkotsu', 'shio']",
    "options": [
      "extend",
      "append",
      "add",
      "merge",
      "concat",
      "join"
    ],
    "hint": "Pista: Revisa los conceptos de .extend().",
    "explanation": ".extend(lista) agrega TODOS los elementos de otra lista al final. .append(lista) agregaría la lista como un solo elemento nested. Con +: menu1 + menu2 retorna nueva lista sin modificar menu1. 🍜",
    "correctAnswer": "extend",
    "orderIndex": 134,
    "coins": 5,
    "xp": 10,
    "theme": "🍜 Fusionando dos menús de ramen",
    "pytoReaction": "¡4 tipos de ramen! El restaurante de Pylearn tiene menú completo 🐍🍜"
  },
  {
    "id": 135,
    "title": "Listas: .sort()",
    "description": "El ranking de streamers muestra None. ¿Por qué?",
    "topic": "Listas básicas - Misión 1",
    "difficulty": "beginner",
    "type": "bug",
    "question": "streamers = [\"xQc\", \"Ibai\", \"Auron\", \"Quackity\"]\nranking = streamers.sort()\nprint(ranking)",
    "options": [
      "streamers no tiene suficientes elementos",
      ".sort() retorna None — modifica en el lugar, no retorna la lista",
      "La lista de strings no se puede ordenar",
      "print no puede mostrar listas"
    ],
    "hint": "Pista: Revisa los conceptos de .sort().",
    "explanation": ".sort() modifica streamers directamente y retorna None. ranking = None. Fix: streamers.sort() y luego print(streamers). O: ranking = sorted(streamers). ¡El ranking de Twitch ya funciona! 📊",
    "correctAnswer": ".sort() retorna None — modifica en el lugar, no retorna la lista",
    "orderIndex": 135,
    "coins": 5,
    "xp": 10,
    "theme": "📊 Ranking confundido de Twitch",
    "pytoReaction": "¡None eliminado! Pylearn salva el ranking de Twitch 🐍"
  }
];

