import type { ExerciseData } from "../types";

export const topicExercises: ExerciseData[] = [
  {
    "id": 136,
    "title": "Listas: Operador in",
    "description": "¿Qué imprime el detector de payasos de Pylearn?",
    "topic": "Listas básicas - Misión 2",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "artistas = [\"mago\", \"acrobata\", \"domador\"]\nif \"payaso\" in artistas:\n    print(\"Hay payasos\")\nelse:\n    print(\"Sin payasos, Pylearn está tranquilo\")",
    "options": [
      "Hay payasos",
      "True",
      "Sin payasos, Pylearn está tranquilo",
      "False"
    ],
    "hint": "Pista: Revisa los conceptos de Operador in.",
    "explanation": "El operador 'in' verifica si un elemento existe en la lista. Retorna True/False. 'payaso' no está en la lista → False → entra al else. También funciona con strings: 'py' in 'python' → True. 🎪",
    "correctAnswer": "Sin payasos, Pylearn está tranquilo",
    "orderIndex": 136,
    "coins": 5,
    "xp": 10,
    "theme": "🎪 ¿Hay payasos en el circo?",
    "pytoReaction": "¡Pylearn odia los payasos! Gracias al operador 'in' 🐍🎪"
  },
  {
    "id": 137,
    "title": "Listas: .index()",
    "description": "Pylearn busca en qué posición está el hechizo 'Lumos' en el grimorio:",
    "topic": "Listas básicas - Misión 2",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "grimorio = [\"Expecto\", \"Lumos\", \"Alohomora\", \"Accio\"]\nposicion = grimorio.___(\"Lumos\")\nprint(posicion)  # → 1",
    "options": [
      "index",
      "find",
      "search",
      "position",
      "indexOf",
      "locate"
    ],
    "hint": "Pista: Revisa los conceptos de .index().",
    "explanation": ".index(valor) retorna el índice de la primera ocurrencia. Si no existe → ValueError. Para buscar sin error: usar 'in' primero y luego .index(). ¡Lumos está en posición 1! 🧙",
    "correctAnswer": "index",
    "orderIndex": 137,
    "coins": 5,
    "xp": 10,
    "theme": "🧙 Buscando hechizo en el grimorio",
    "pytoReaction": "¡Lumos encontrado en pos 1! Pylearn ilumina la mazmorra 🐍✨"
  },
  {
    "id": 138,
    "title": "Listas: .count()",
    "description": "¿Cuántos pingüinos Emperor hay en el censo?",
    "topic": "Listas básicas - Misión 2",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "censo = [\"Emperor\", \"Gentoo\", \"Emperor\", \"Adelie\", \"Emperor\", \"Gentoo\"]\nprint(censo.count(\"Emperor\"))",
    "options": [
      "2",
      "3",
      "6",
      "1"
    ],
    "hint": "Pista: Revisa los conceptos de .count().",
    "explanation": ".count(valor) cuenta cuántas veces aparece el valor en la lista. 'Emperor' aparece en índices 0, 2 y 4 → 3 veces. Funciona también en strings: 'banana'.count('a') = 3. 🐧",
    "correctAnswer": "3",
    "orderIndex": 138,
    "coins": 5,
    "xp": 10,
    "theme": "🐧 Censo de pingüinos en la Antártida",
    "pytoReaction": "¡3 pingüinos Emperor! Pylearn los protege a todos 🐍🐧"
  },
  {
    "id": 139,
    "title": "Listas: List comprehension con transformación",
    "description": "¿Qué lista crea el convertidor de Pylearn?",
    "topic": "Listas básicas - Misión 2",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "canciones = [\"despacito\", \"tití\", \"hawái\"]\nmayus = [c.upper() for c in canciones]\nprint(mayus)",
    "options": [
      "[\"despacito\", \"tití\", \"hawái\"]",
      "[\"DESPACITO\", \"TITÍ\", \"HAWÁI\"]",
      "DESPACITO TITÍ HAWÁI",
      "[upper(\"despacito\"), upper(\"tití\"), upper(\"hawái\")]"
    ],
    "hint": "Pista: Revisa los conceptos de List comprehension con transformación.",
    "explanation": "El list comprehension aplica .upper() a CADA elemento y crea una nueva lista con los resultados. Es equivalente a un for loop que hace .append() en cada iteración. ¡Setlist en mayúsculas! 🎵",
    "correctAnswer": "[\"DESPACITO\", \"TITÍ\", \"HAWÁI\"]",
    "orderIndex": 139,
    "coins": 5,
    "xp": 10,
    "theme": "🎵 Convirtiendo nombres de canciones",
    "pytoReaction": "¡DESPACITO! Pylearn canta a todo volumen 🐍🎵"
  },
  {
    "id": 140,
    "title": "Listas: Slicing de listas",
    "description": "Pylearn solo puede ver los 3 primeros episodios antes del spoiler. ¿Cuál slice usar?",
    "topic": "Listas básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "multiple_choice",
    "question": "episodios = [\"Ep1\", \"Ep2\", \"Ep3\", \"Ep4\", \"Ep5\", \"Ep6\"]",
    "options": [
      "episodios[0:2]",
      "episodios[:3]",
      "episodios[1:3]",
      "episodios[0:4]"
    ],
    "hint": "Pista: Revisa los conceptos de Slicing de listas.",
    "explanation": "[:3] es equivalente a [0:3] → toma los primeros 3 elementos (índices 0, 1, 2). El 3 no se incluye. Si omites el inicio en el slice, Python asume 0 automáticamente 🎬",
    "correctAnswer": "episodios[:3]",
    "orderIndex": 140,
    "coins": 12,
    "xp": 20,
    "theme": "🎬 Trailer spoileado",
    "pytoReaction": "¡Pylearn salva los Ep1, Ep2 y Ep3! Sin spoilers 🐍🎬"
  },
  {
    "id": 141,
    "title": "Listas: zip() con enumerate()",
    "description": "¿Qué imprime el generador de resultados del torneo?",
    "topic": "Listas básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "predict_output",
    "question": "surfistas = [\"Medina\", \"Italo\", \"Kanoa\"]\npuntos = [95.4, 88.2, 91.7]\nfor pos, (nombre, pts) in enumerate(zip(surfistas, puntos), 1):\n    print(f\"{pos}. {nombre}: {pts}\")",
    "options": [
      "0. Medina: 95.4\\n1. Italo: 88.2\\n2. Kanoa: 91.7",
      "1. Medina: 95.4\\n2. Italo: 88.2\\n3. Kanoa: 91.7",
      "(1, Medina): 95.4\\n...",
      "Error: zip y enumerate no se combinan"
    ],
    "hint": "Pista: Revisa los conceptos de zip() con enumerate().",
    "explanation": "zip() empareja surfistas con puntos, enumerate() les agrega posición (start=1). El unpacking (nombre, pts) desempaqueta cada tupla de zip. ¡zip + enumerate es combo pro! 🏄",
    "correctAnswer": "1. Medina: 95.4\n2. Italo: 88.2\n3. Kanoa: 91.7",
    "orderIndex": 141,
    "coins": 12,
    "xp": 20,
    "theme": "🏄 Tabla de resultados del torneo de surf",
    "pytoReaction": "¡Tabla perfecta! Medina gana, Pylearn queda 4to... 🐍🏄"
  },
  {
    "id": 142,
    "title": "Listas: Listas anidadas",
    "description": "¿Cómo accede Pylearn a la ubicación de la fila 2, columna 3 del mapa?",
    "topic": "Listas básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "multiple_choice",
    "question": "mapa = [\n    [\"bosque\", \"rio\", \"montaña\"],\n    [\"ciudad\", \"bunker\", \"puente\"],\n    [\"playa\", \"cueva\", \"torre\"]\n]\n",
    "options": [
      "mapa[3][2]",
      "mapa[1][2]",
      "mapa[2][3]",
      "mapa[2][2]"
    ],
    "hint": "Pista: Revisa los conceptos de Listas anidadas.",
    "explanation": "Los índices empiezan en 0. Fila 2 = índice 1. Columna 3 = índice 2. mapa[1][2] = 'puente'. El primer [] selecciona la fila (lista), el segundo [] el elemento dentro de esa fila. ¡Pylearn aterriza en el puente! 🎮",
    "correctAnswer": "mapa[1][2]",
    "orderIndex": 142,
    "coins": 12,
    "xp": 20,
    "theme": "🎮 Tablero de Fortnite (mapa 3x3)",
    "pytoReaction": "¡Pylearn aterriza en el puente! Estrategia de nivel pro 🐍🎮"
  },
  {
    "id": 143,
    "title": "Listas: Desempaquetado extendido",
    "description": "¿Qué imprime el desempaquetador de stats?",
    "topic": "Listas básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "predict_output",
    "question": "stats = [100, 85, 72, 91, 68, 77]\nprimero, *medio, ultimo = stats\nprint(primero)\nprint(len(medio))\nprint(ultimo)",
    "options": [
      "100\\n4\\n77",
      "100\\n6\\n77",
      "[100]\\n[85,72,91,68]\\n[77]",
      "Error: * solo funciona en funciones"
    ],
    "hint": "Pista: Revisa los conceptos de Desempaquetado extendido.",
    "explanation": "El * en desempaquetado captura 'todo lo del medio' como lista. primero=100, medio=[85,72,91,68](4 elementos), ultimo=77. ¡Desempaquetado extendido: el truco más elegante de Python! 🎮",
    "correctAnswer": "100\n4\n77",
    "orderIndex": 143,
    "coins": 12,
    "xp": 20,
    "theme": "🎮 Capturando estadísticas de Fortnite",
    "pytoReaction": "¡100 de escudo, 77 de vida! Pylearn analiza sus stats 🐍🎮"
  },
  {
    "id": 144,
    "title": "Listas: List comprehension",
    "description": "El entrenador filtra solo a los jugadores con más de 80 puntos. ¿Cuál es la lista resultante?",
    "topic": "Listas básicas - Misión 2",
    "difficulty": "advanced",
    "type": "predict_output",
    "question": "puntos = [55, 88, 72, 95, 61, 90]\ncampeones = [p for p in puntos if p > 80]\nprint(campeones)",
    "options": [
      "[55, 88, 72, 95, 61, 90]",
      "[88, 95, 90]",
      "[55, 72, 61]",
      "[88, 90]"
    ],
    "hint": "Pista: Revisa los conceptos de List comprehension.",
    "explanation": "El list comprehension [p for p in puntos if p > 80] crea una nueva lista con solo los valores mayores a 80. 55✗, 88✓, 72✗, 95✓, 61✗, 90✓ → [88, 95, 90]. ¡Magia pythónica! 🏋️",
    "correctAnswer": "[88, 95, 90]",
    "orderIndex": 144,
    "coins": 25,
    "xp": 35,
    "theme": "🏋️ Filtro de campeones",
    "pytoReaction": "¡Solo quedan los cracks! Pylearn tiene 95 obviamente 🐍💪"
  },
  {
    "id": 145,
    "title": "Listas: sorted() y len()",
    "description": "Pylearn ordena el ranking de mayor a menor puntaje:",
    "topic": "Listas básicas - Misión 2",
    "difficulty": "advanced",
    "type": "fill_blank",
    "question": "scores = [340, 120, 580, 210, 450]\nranking = ___(scores, ___=True)\nprint(ranking)",
    "options": [
      "sorted",
      "sort",
      "reverse",
      "reversed",
      "True",
      "False",
      "key",
      "desc"
    ],
    "hint": "Pista: Revisa los conceptos de sorted() y len().",
    "explanation": "sorted(lista, reverse=True) retorna una NUEVA lista ordenada de mayor a menor. .sort() ordena en el lugar (no retorna nada). reverse=True invierte el orden. ¡El ranking queda perfecto! 🏅",
    "correctAnswer": "sorted,reverse",
    "orderIndex": 145,
    "coins": 25,
    "xp": 35,
    "theme": "🏅 Ranking automático",
    "pytoReaction": "¡Ranking listo! Pylearn en el #1 como siempre 🐍🥇"
  },
  {
    "id": 146,
    "title": "Listas: Aplanar lista con sum()",
    "description": "¿Qué produce el aplanador de galaxias?",
    "topic": "Listas básicas - Misión 2",
    "difficulty": "advanced",
    "type": "predict_output",
    "question": "galaxias = [[\"Vía Láctea\", \"Andrómeda\"], [\"Triangulum\"], [\"Centaurus A\", \"M87\"]]\nplana = sum(galaxias, [])\nprint(len(plana))",
    "options": [
      "3",
      "4",
      "5",
      "6"
    ],
    "hint": "Pista: Revisa los conceptos de Aplanar lista con sum().",
    "explanation": "sum(lista_de_listas, []) aplana una lista de listas. Empieza con [] y concatena cada sublista. 2+1+2=5 elementos en total. Para listas muy grandes usa itertools.chain.from_iterable (más eficiente). 🌌",
    "correctAnswer": "5",
    "orderIndex": 146,
    "coins": 25,
    "xp": 35,
    "theme": "🌌 Mapeando galaxias anidadas",
    "pytoReaction": "¡5 galaxias en lista plana! Pylearn las visita con su cohete 🐍🌌"
  },
  {
    "id": 147,
    "title": "Listas: Algoritmo de búsqueda binaria",
    "description": "¿Cuántas comparaciones máximo necesita la búsqueda binaria para encontrar un libro entre 1 millón?",
    "topic": "Listas básicas - Misión 2",
    "difficulty": "advanced",
    "type": "multiple_choice",
    "question": "import math\nlibros = 1_000_000\nmax_comparaciones = math.ceil(math.log2(libros))\nprint(max_comparaciones)",
    "options": [
      "1000",
      "500000",
      "20",
      "100"
    ],
    "hint": "Pista: Revisa los conceptos de Algoritmo de búsqueda binaria.",
    "explanation": "La búsqueda binaria es O(log₂n). log₂(1,000,000) ≈ 19.93 → ceil = 20. Una lista ORDENADA de 1 millón se busca en máximo 20 pasos. Lineal sería 1,000,000 pasos. ¡Eso es algoritmia! 📚",
    "correctAnswer": "20",
    "orderIndex": 147,
    "coins": 25,
    "xp": 35,
    "theme": "📚 Biblioteca de Pylearn con millones de libros",
    "pytoReaction": "¡20 pasos para 1M de libros! Pylearn ama los algoritmos 🐍📚"
  }
];

