import type { ExerciseData } from "../types";

export const topicExercises: ExerciseData[] = [
  {
    "id": 148,
    "title": "Bucles: for básico",
    "description": "Pylearn reparte donuts a sus amigos. ¿Cuántas veces se imprime '¡Donut!'?",
    "topic": "Bucles básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "amigos = [\"Ana\", \"Luis\", \"Carla\"]\nfor amigo in amigos:\n    print(\"¡Donut!\")",
    "options": [
      "1 vez",
      "2 veces",
      "3 veces",
      "0 veces"
    ],
    "hint": "Pista: Revisa los conceptos de for básico.",
    "explanation": "El for recorre cada elemento de la lista. amigos tiene 3 elementos → el cuerpo se ejecuta 3 veces. ¡Un donut para Ana, uno para Luis y uno para Carla! 🍩",
    "correctAnswer": "3 veces",
    "orderIndex": 148,
    "coins": 5,
    "xp": 10,
    "theme": "🍩 Repartiendo donuts",
    "pytoReaction": "¡Correcto! Pylearn se quedó con los 3 de repuesto 🐍🍩"
  },
  {
    "id": 149,
    "title": "Bucles: range()",
    "description": "¿Qué imprime la cuenta regresiva del cohete de Pylearn?",
    "topic": "Bucles básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "for i in range(5, 0, -1):\n    print(i)\nprint(\"🚀 DESPEGUE\")",
    "options": [
      "5 4 3 2 1 0 🚀 DESPEGUE",
      "5 4 3 2 1 🚀 DESPEGUE",
      "0 1 2 3 4 🚀 DESPEGUE",
      "1 2 3 4 5 🚀 DESPEGUE"
    ],
    "hint": "Pista: Revisa los conceptos de range().",
    "explanation": "range(5, 0, -1) va de 5 hasta 1 (el 0 NO se incluye) restando 1 cada vez. El print de despegue está FUERA del for, se imprime solo al final. ¡Houston, tenemos un loop! 🚀",
    "correctAnswer": "5 4 3 2 1 🚀 DESPEGUE",
    "orderIndex": 149,
    "coins": 5,
    "xp": 10,
    "theme": "🚀 Lanzamiento cohete",
    "pytoReaction": "¡Pylearn ya está en órbita! 🐍🚀"
  },
  {
    "id": 150,
    "title": "Bucles: while",
    "description": "El juego de Pylearn no termina nunca. ¿Por qué hay un bucle infinito?",
    "topic": "Bucles básicas - Misión 1",
    "difficulty": "beginner",
    "type": "bug",
    "question": "vidas = 3\nwhile vidas > 0:\n    print(f\"Vidas: {vidas}\")\n    vidas == vidas - 1",
    "options": [
      "vidas empieza en 3, debería ser 0",
      "El while debería ser un for",
      "Se usa == en vez de = para restar vidas",
      "El print está dentro del while"
    ],
    "hint": "Pista: Revisa los conceptos de while.",
    "explanation": "vidas == vidas - 1 es una COMPARACIÓN (¿son iguales?), no una asignación. Por eso vidas nunca cambia y el while nunca termina. Correcto: vidas = vidas - 1 o vidas -= 1 🎮",
    "correctAnswer": "Se usa == en vez de = para restar vidas",
    "orderIndex": 150,
    "coins": 5,
    "xp": 10,
    "theme": "🎮 Vidas infinitas",
    "pytoReaction": "¡Game Over (del bug)! Pylearn pudo jugar por fin 🐍🎮"
  },
  {
    "id": 151,
    "title": "Bucles: while",
    "description": "¿Cuántas veces imprime 'Ñom' el bucle de Pylearn?",
    "topic": "Bucles básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "porciones = 4\nwhile porciones > 0:\n    print(\"Ñom\")\n    porciones -= 1",
    "options": [
      "3 veces",
      "4 veces",
      "5 veces",
      "Infinitas veces"
    ],
    "hint": "Pista: Revisa los conceptos de while.",
    "explanation": "porciones empieza en 4. Cada vez que se imprime 'Ñom', porciones baja en 1 (4→3→2→1→0). Cuando llega a 0, la condición porciones > 0 es False y el while para. ¡4 Ñoms! 🍕",
    "correctAnswer": "4 veces",
    "orderIndex": 151,
    "coins": 5,
    "xp": 10,
    "theme": "🍕 Comiendo pizza hasta el fin",
    "pytoReaction": "¡Ñom ñom ñom ñom! Pylearn terminó toda la pizza 🐍🍕"
  },
  {
    "id": 152,
    "title": "Bucles: for con string",
    "description": "¿Cuántas veces itera el for loop sobre la contraseña?",
    "topic": "Bucles básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "clave = \"Python\"\nfor letra in clave:\n    print(letra)",
    "options": [
      "1 vez",
      "5 veces",
      "6 veces",
      "0 veces"
    ],
    "hint": "Pista: Revisa los conceptos de for con string.",
    "explanation": "El for loop en Python puede iterar sobre CUALQUIER iterable — incluyendo strings. 'Python' tiene 6 caracteres → 6 iteraciones, imprimiendo P, y, t, h, o, n en líneas separadas. 🔐",
    "correctAnswer": "6 veces",
    "orderIndex": 152,
    "coins": 5,
    "xp": 10,
    "theme": "🔐 Descifrador de contraseña carácter por carácter",
    "pytoReaction": "¡P-y-t-h-o-n! Pylearn descifra letra por letra 🐍"
  },
  {
    "id": 153,
    "title": "Bucles: for con string",
    "description": "¿Qué imprime el analizador de vocales de Pylearn?",
    "topic": "Bucles básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "cancion = \"rock\"\nvocales = 0\nfor c in cancion:\n    if c in \"aeiou\":\n        vocales += 1\nprint(vocales)",
    "options": [
      "0",
      "1",
      "2",
      "4"
    ],
    "hint": "Pista: Revisa los conceptos de for con string.",
    "explanation": "Itera cada carácter de 'rock': r(no), o(sí +=1), c(no), k(no). Total: 1 vocal. Iterar sobre string + in sobre string = combo poderoso para análisis de texto. 🎸",
    "correctAnswer": "1",
    "orderIndex": 153,
    "coins": 5,
    "xp": 10,
    "theme": "🎸 Analizando acordes de rock",
    "pytoReaction": "¡1 vocal en 'rock'! El análisis fonético de Pylearn es preciso 🐍🎸"
  },
  {
    "id": 154,
    "title": "Bucles: for con dict",
    "description": "Pylearn revisa cada app con sus notificaciones pendientes:",
    "topic": "Bucles básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "notifs = {\"Discord\": 14, \"WhatsApp\": 3, \"Gmail\": 99}\nfor app ___ notifs:\n    print(f\"{app}: {notifs[app]}\")",
    "options": [
      "in",
      "of",
      "from",
      "within",
      "at",
      ":"
    ],
    "hint": "Pista: Revisa los conceptos de for con dict.",
    "explanation": "for key in dict itera sobre las CLAVES del diccionario. Para obtener el valor: dict[key]. Para iterar claves y valores juntos: for key, val in dict.items(). ¡Pylearn tiene 116 notificaciones pendientes! 📱",
    "correctAnswer": "in",
    "orderIndex": 154,
    "coins": 5,
    "xp": 10,
    "theme": "📱 Revisando notificaciones de Discord",
    "pytoReaction": "¡99 de Gmail! Pylearn nunca revisa su correo 🐍😅"
  },
  {
    "id": 155,
    "title": "Bucles: while con condición compuesta",
    "description": "¿Cuándo para de entrenar Goku?",
    "topic": "Bucles básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "energia = 100\nentrenamientos = 0\nwhile energia > 20 and entrenamientos < 5:\n    energia -= 25\n    entrenamientos += 1\nprint(entrenamientos)",
    "options": [
      "3",
      "4",
      "5",
      "2"
    ],
    "hint": "Pista: Revisa los conceptos de while con condición compuesta.",
    "explanation": "Iter1: 100→75, ent=1. Iter2: 75→50, ent=2. Iter3: 50→25, ent=3. Iter4: 25→0, ent=4. Check iter5: energia=0, 0>20 = False → para. Total: 4 entrenamientos. ¡Goku necesita senzu! ⚡",
    "correctAnswer": "4",
    "orderIndex": 155,
    "coins": 5,
    "xp": 10,
    "theme": "⚡ Entrenamiento de Dragon Ball",
    "pytoReaction": "¡4 entrenamientos! Goku Pylearn ya puede pelear contra Cell 🐍⚡"
  },
  {
    "id": 156,
    "title": "Bucles: zip()",
    "description": "Pylearn empareja nadadores con sus tiempos usando zip:",
    "topic": "Bucles básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "nadadores = [\"Phelps\", \"Dressel\", \"Milak\"]\ntiempos = [51.1, 49.5, 50.7]\nfor nombre, seg in ___(nadadores, tiempos):\n    print(f\"{nombre}: {seg}s\")",
    "options": [
      "zip",
      "pair",
      "match",
      "combine",
      "merge",
      "enumerate"
    ],
    "hint": "Pista: Revisa los conceptos de zip().",
    "explanation": "zip(lista1, lista2) empareja elementos en el mismo índice como tuplas. Itera hasta que la lista más corta se acaba. Ideal para procesar dos listas relacionadas en paralelo. 🏊",
    "correctAnswer": "zip",
    "orderIndex": 156,
    "coins": 5,
    "xp": 10,
    "theme": "🏊 Resultados de natación",
    "pytoReaction": "¡Dressel gana con 49.5s! Pylearn también compite a 3 min 🐍🏊"
  },
  {
    "id": 157,
    "title": "Bucles: List comprehension con condición",
    "description": "¿Qué lista produce el filtro de animales peligrosos?",
    "topic": "Bucles básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "animales = [\"cebra\", \"leon\", \"jirafa\", \"leopardo\", \"gnu\"]\npeligrosos = [a for a in animales if len(a) > 5]\nprint(peligrosos)",
    "options": [
      "[\"leon\", \"leopardo\"]",
      "[\"leopardo\"]",
      "[\"jirafa\", \"leopardo\"]",
      "[\"cebra\", \"jirafa\", \"leopardo\"]"
    ],
    "hint": "Pista: Revisa los conceptos de List comprehension con condición.",
    "explanation": "Filtra los que tienen más de 5 letras. cebra=5(no), leon=4(no), jirafa=6(sí), leopardo=8(sí), gnu=3(no). Resultado: jirafa y leopardo. ¡El safari de Pylearn tiene criterios precisos! 🦁",
    "correctAnswer": "[\"jirafa\", \"leopardo\"]",
    "orderIndex": 157,
    "coins": 5,
    "xp": 10,
    "theme": "🦁 Filtrando animales del safari",
    "pytoReaction": "¡2 animales peligrosos! Pylearn se aleja del jeep igual 🐍🦁"
  },
  {
    "id": 158,
    "title": "Bucles: range() con step",
    "description": "La numeradora de galletas de Pylearn salta números impares. ¿Dónde está el error?",
    "topic": "Bucles básicas - Misión 1",
    "difficulty": "beginner",
    "type": "bug",
    "question": "for i in range(0, 10, 1):\n    if i % 2 == 0:\n        print(i)",
    "options": [
      "range(0, 10, 1) debería ser range(0, 10, 2) para mayor eficiencia",
      "i % 2 == 0 no detecta pares correctamente",
      "El loop debería empezar en 1",
      "No hay error, pero range(0,10,2) es más pythónico"
    ],
    "hint": "Pista: Revisa los conceptos de range() con step.",
    "explanation": "El código funciona correctamente (step=1 y filtro con %). Pero range(0,10,2) es más eficiente y directo: va de 2 en 2. range(start, stop, step) permite saltar directamente los impares. 🧁",
    "correctAnswer": "No hay error, pero range(0,10,2) es más pythónico",
    "orderIndex": 158,
    "coins": 5,
    "xp": 10,
    "theme": "🧁 Numerando galletas pares",
    "pytoReaction": "¡Código correcto pero optimizable! Pylearn aprende el Zen de Python 🐍"
  }
];

