import type { ExerciseData } from "../types";

export const topicExercises: ExerciseData[] = [
  {
    "id": 159,
    "title": "Bucles: Acumulador en bucle",
    "description": "¿Cuántos caracteres en total tienen todos los mensajes?",
    "topic": "Bucles básicas - Misión 2",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "mensajes = [\"GG\", \"EZ\", \"Pylearn ganó\", \"gg\"]\ntotal = 0\nfor m in mensajes:\n    total += len(m)\nprint(total)",
    "options": [
      "4",
      "15",
      "16",
      "14"
    ],
    "hint": "Pista: Revisa los conceptos de Acumulador en bucle.",
    "explanation": "GG=2, EZ=2, 'Pylearn ganó'=9 (con espacio y ó), gg=2. Total: 2+2+9+2=15. El patrón acumulador (variable=0, luego +=) es fundamental en programación. ¡El chat de Twitch tiene 15 caracteres! 💬",
    "correctAnswer": "15",
    "orderIndex": 159,
    "coins": 5,
    "xp": 10,
    "theme": "💬 Contando palabras del Twitch chat",
    "pytoReaction": "¡15 caracteres de hype! El chat de Pylearn explota 🐍💬"
  },
  {
    "id": 160,
    "title": "Bucles: break y continue",
    "description": "¿Qué nombres imprime el detector de impostores?",
    "topic": "Bucles básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "predict_output",
    "question": "tripulacion = [\"Ana\", \"Luis\", \"Pylearn (impostor)\", \"María\"]\nfor nombre in tripulacion:\n    if nombre == \"Pylearn (impostor)\":\n        continue\n    print(nombre)",
    "options": [
      "Ana, Luis, Pylearn (impostor), María",
      "Ana, Luis, María",
      "Pylearn (impostor)",
      "Ana, Luis"
    ],
    "hint": "Pista: Revisa los conceptos de break y continue.",
    "explanation": "continue salta SOLO la iteración actual y continúa con la siguiente. Cuando encuentra a 'Pylearn (impostor)' lo salta sin imprimirlo y sigue con 'María'. ¡El impostor queda expuesto pero libre! 🕵️",
    "correctAnswer": "Ana\nLuis\nMaría",
    "orderIndex": 160,
    "coins": 12,
    "xp": 20,
    "theme": "🕵️ Buscando al impostor",
    "pytoReaction": "¡Era Pylearn el impostor! Pero continue lo salvó... esta vez 🐍🔪"
  },
  {
    "id": 161,
    "title": "Bucles: enumerate()",
    "description": "Pylearn quiere mostrar el ranking numerado de streamers:",
    "topic": "Bucles básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "fill_blank",
    "question": "streamers = [\"xQc\", \"Ibai\", \"Auron\"]\nfor pos, nombre in ___(streamers, 1):\n    print(f\"{pos}° {nombre}\")",
    "options": [
      "enumerate",
      "numbered",
      "index",
      "zip",
      "range",
      "count"
    ],
    "hint": "Pista: Revisa los conceptos de enumerate().",
    "explanation": "enumerate(lista, start=1) te da el índice Y el valor a la vez. Con start=1 el conteo empieza desde 1 en lugar de 0. ¡Perfecto para rankings y listas numeradas! 🏅",
    "correctAnswer": "enumerate",
    "orderIndex": 161,
    "coins": 12,
    "xp": 20,
    "theme": "🏅 Top de streamers",
    "pytoReaction": "¡1° xQc, 2° Ibai, 3° Auron! Pylearn sería el 0° 🐍🎮"
  },
  {
    "id": 162,
    "title": "Bucles: any() y all()",
    "description": "¿Qué imprime el validador del formulario de Pylearn?",
    "topic": "Bucles básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "multiple_choice",
    "question": "campos = {\"nombre\": \"Pylearn\", \"email\": \"\", \"edad\": \"15\"}\nvalido = all(campos.values())\nprint(\"Formulario válido\" if valido else \"Campos vacíos\")",
    "options": [
      "Formulario válido",
      "Campos vacíos",
      "True",
      "Error: all() no funciona con strings"
    ],
    "hint": "Pista: Revisa los conceptos de any() y all().",
    "explanation": "all() retorna True si TODOS los elementos son truthy. all() sobre .values() chequea nombre='Pylearn'(truthy), email=''(FALSY!), edad='15'(truthy). Como email es vacío → False → 'Campos vacíos'. 🔍",
    "correctAnswer": "Campos vacíos",
    "orderIndex": 162,
    "coins": 12,
    "xp": 20,
    "theme": "✅ Validador de formulario de registro",
    "pytoReaction": "¡Email vacío detectado! Pylearn protege el formulario 🐍✅"
  },
  {
    "id": 163,
    "title": "Bucles: Generador con sum()",
    "description": "¿Cuánto daño total hacen los hechizos que superan 50?",
    "topic": "Bucles básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "predict_output",
    "question": "hechizos = [30, 80, 45, 90, 20, 75]\ndanio_total = sum(d for d in hechizos if d > 50)\nprint(danio_total)",
    "options": [
      "245",
      "340",
      "260",
      "245"
    ],
    "hint": "Pista: Revisa los conceptos de Generador con sum().",
    "explanation": "sum() con generator expression: evalúa la condición y suma solo los que pasan. 80+90+75 = 245. Los hechizos de 30, 45 y 20 no cuentan. Es más eficiente que crear una lista intermedia. ⚡",
    "correctAnswer": "245",
    "orderIndex": 163,
    "coins": 12,
    "xp": 20,
    "theme": "⚡ Calculando daño total de hechizos",
    "pytoReaction": "¡245 de daño total! El mago Pylearn arrasa 🐍⚡"
  },
  {
    "id": 164,
    "title": "Bucles: for else",
    "description": "¿Qué imprime Luffy buscando el One Piece?",
    "topic": "Bucles básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "multiple_choice",
    "question": "islas = [\"Alabasta\", \"Skypiea\", \"Water 7\", \"Fishman\"]\nfor isla in islas:\n    if isla == \"Raftel\":\n        print(\"¡One Piece encontrado!\")\n        break\nelse:\n    print(\"One Piece no está aquí...\")",
    "options": [
      "¡One Piece encontrado!",
      "One Piece no está aquí...",
      "No imprime nada",
      "Error: for no puede tener else"
    ],
    "hint": "Pista: Revisa los conceptos de for else.",
    "explanation": "El 'else' de un for se ejecuta SOLO si el loop terminó sin break (es decir, sin encontrar lo que buscaba). Como 'Raftel' no está en la lista, no hay break → se ejecuta el else. ¡Luffy sigue buscando! 🌊",
    "correctAnswer": "One Piece no está aquí...",
    "orderIndex": 164,
    "coins": 12,
    "xp": 20,
    "theme": "🔍 Buscando el tesoro de One Piece",
    "pytoReaction": "¡El One Piece existe! Pylearn le pasa el mapa a Luffy 🐍🌊"
  },
  {
    "id": 165,
    "title": "Bucles: Bucles anidados",
    "description": "¿Cuántas combinaciones posibles imprime el juego de dados de Pylearn?",
    "topic": "Bucles básicas - Misión 2",
    "difficulty": "advanced",
    "type": "multiple_choice",
    "question": "for dado1 in range(1, 4):\n    for dado2 in range(1, 4):\n        print(f\"{dado1}-{dado2}\")",
    "options": [
      "3 combinaciones",
      "6 combinaciones",
      "9 combinaciones",
      "12 combinaciones"
    ],
    "hint": "Pista: Revisa los conceptos de Bucles anidados.",
    "explanation": "El loop externo corre 3 veces (1,2,3). Por CADA iteración, el interno corre 3 veces. 3×3=9 combinaciones. Los bucles anidados MULTIPLICAN. ¡El casino de Pylearn funciona! 🎲",
    "correctAnswer": "9 combinaciones",
    "orderIndex": 165,
    "coins": 25,
    "xp": 35,
    "theme": "🎲 Dados del destino",
    "pytoReaction": "¡9 combinaciones y Pylearn ganó en todas! 🐍🎲"
  },
  {
    "id": 166,
    "title": "Bucles: while + break",
    "description": "¿Cuánto imprime la IA antes de encontrar la respuesta?",
    "topic": "Bucles básicas - Misión 2",
    "difficulty": "advanced",
    "type": "predict_output",
    "question": "intentos = 0\nrespuesta = False\nwhile True:\n    intentos += 1\n    if intentos == 3:\n        respuesta = True\n        break\nprint(f\"Encontré en {intentos} intentos\")",
    "options": [
      "Encontré en 1 intentos",
      "Encontré en 2 intentos",
      "Encontré en 3 intentos",
      "Loop infinito"
    ],
    "hint": "Pista: Revisa los conceptos de while + break.",
    "explanation": "while True crea un loop infinito. El break lo detiene cuando intentos llega a 3. El print está FUERA del while, se ejecuta solo una vez al final. ¡La IA tardó exactamente 3 intentos! 🤖",
    "correctAnswer": "Encontré en 3 intentos",
    "orderIndex": 166,
    "coins": 25,
    "xp": 35,
    "theme": "🤖 IA buscando respuesta",
    "pytoReaction": "¡La IA de Pylearn es eficiente! Solo 3 intentos 🐍🤖"
  },
  {
    "id": 167,
    "title": "Bucles: Itertools — product conceptual",
    "description": "¿Cuántas líneas imprime el combinador de equipos de Pylearn?",
    "topic": "Bucles básicas - Misión 2",
    "difficulty": "advanced",
    "type": "predict_output",
    "question": "roles = [\"tank\", \"dps\", \"healer\"]\nespecialidades = [\"fuego\", \"hielo\"]\ncombo = [(r, e) for r in roles for e in especialidades]\nprint(len(combo))",
    "options": [
      "3",
      "5",
      "6",
      "9"
    ],
    "hint": "Pista: Revisa los conceptos de Itertools — product conceptual.",
    "explanation": "El list comprehension con dos for genera el producto cartesiano: cada rol con cada especialidad. 3 roles × 2 especialidades = 6 combinaciones. Es equivalente a itertools.product. ¡6 builds diferentes! 🎲",
    "correctAnswer": "6",
    "orderIndex": 167,
    "coins": 25,
    "xp": 35,
    "theme": "🎲 Generador de combinaciones de equipos",
    "pytoReaction": "¡6 combinaciones épicas! Pylearn elige tank-fuego obviamente 🐍🔥"
  },
  {
    "id": 168,
    "title": "Bucles: Generador personalizado",
    "description": "Pylearn crea un generador que produce olas de tamaño creciente sin guardarlas en memoria:",
    "topic": "Bucles básicas - Misión 2",
    "difficulty": "advanced",
    "type": "fill_blank",
    "question": "def generar_olas(max_ola):\n    altura = 1\n    while altura <= max_ola:\n        ___ altura\n        altura += 1\n\nfor ola in generar_olas(3):\n    print(f\"Ola de {ola}m\")",
    "options": [
      "yield",
      "return",
      "print",
      "give",
      "send",
      "emit"
    ],
    "hint": "Pista: Revisa los conceptos de Generador personalizado.",
    "explanation": "yield convierte la función en un generador: pausa la función y devuelve el valor, pero recuerda el estado para la próxima llamada. No guarda todo en memoria — genera uno a la vez. Ideal para secuencias largas o infinitas. 🌊",
    "correctAnswer": "yield",
    "orderIndex": 168,
    "coins": 25,
    "xp": 35,
    "theme": "🌊 Generador infinito de olas de surf",
    "pytoReaction": "¡Ola de 1m, 2m, 3m! Pylearn surfa el generador 🐍🌊"
  },
  {
    "id": 169,
    "title": "Bucles: Bucle con sets",
    "description": "¿Cuántas skins únicas tiene Pylearn en total?",
    "topic": "Bucles básicas - Misión 2",
    "difficulty": "advanced",
    "type": "predict_output",
    "question": "coleccion1 = {\"Galaxy\", \"Drift\", \"Raven\"}\ncoleccion2 = {\"Drift\", \"Cuddle\", \"Galaxy\", \"Omega\"}\ntodas = coleccion1 | coleccion2\nprint(len(todas))",
    "options": [
      "7",
      "5",
      "4",
      "6"
    ],
    "hint": "Pista: Revisa los conceptos de Bucle con sets.",
    "explanation": "| entre sets es la UNIÓN: todos los elementos únicos de ambos conjuntos. 'Galaxy' y 'Drift' aparecen en ambas pero el set no duplica. Total: Galaxy, Drift, Raven, Cuddle, Omega = 5 skins únicas. ¡Sets son perfectos para esto! 🎮",
    "correctAnswer": "5",
    "orderIndex": 169,
    "coins": 25,
    "xp": 35,
    "theme": "🎮 Detector de cartas únicas en Fortnite",
    "pytoReaction": "¡5 skins únicas! Pylearn tiene el mejor armario de Fortnite 🐍🎮"
  }
];

