import type { ExerciseData } from "../types";

export const topicExercises: ExerciseData[] = [
  {
    "id": 170,
    "title": "Funciones: def",
    "description": "Chef Pylearn quiere guardar su receta de pizza como una función reutilizable. ¿Cuál es la sintaxis correcta?",
    "topic": "Funciones básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "Chef Pylearn quiere guardar su receta de pizza como una función reutilizable. ¿Cuál es la sintaxis correcta?",
    "options": [
      "function hacer_pizza():\n    ...",
      "def hacer_pizza():\n    ...",
      "create hacer_pizza():\n    ...",
      "recipe hacer_pizza():\n    ..."
    ],
    "hint": "Pista: Revisa los conceptos de def.",
    "explanation": "¡def es la palabra mágica en Python! def nombre(): con el cuerpo indentado. Las funciones guardan recetas que puedes usar mil veces sin reescribir. ¡Chef Pylearn aprueba! 👨‍🍳",
    "correctAnswer": "def hacer_pizza():\n    ...",
    "orderIndex": 170,
    "coins": 5,
    "xp": 10,
    "theme": "👨‍🍳 Receta secreta de Pylearn",
    "pytoReaction": "¡La receta está guardada! Pylearn ya puede cocinar para siempre 🐍🍕"
  },
  {
    "id": 171,
    "title": "Funciones: return",
    "description": "La función debe DEVOLVER el valor calculado (no solo imprimirlo):",
    "topic": "Funciones básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "def calcular_propina(total):\n    propina = total * 0.10\n    ___ propina",
    "options": [
      "return",
      "print",
      "give",
      "output",
      "send",
      "yield"
    ],
    "hint": "Pista: Revisa los conceptos de return.",
    "explanation": "return envía el resultado de vuelta al que llamó la función. Sin return → la función devuelve None (nada útil). ¡return es como el plato terminado que el chef entrega al cliente! 💰",
    "correctAnswer": "return",
    "orderIndex": 171,
    "coins": 5,
    "xp": 10,
    "theme": "💰 Calculadora de propinas",
    "pytoReaction": "¡La propina está calculada y entregada! Pylearn es generoso 🐍💸"
  },
  {
    "id": 172,
    "title": "Funciones: Parámetros y argumentos",
    "description": "¿Qué imprime el sistema de bienvenida del juego?",
    "topic": "Funciones básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "def bienvenida(nombre, nivel):\n    print(f\"¡Hola {nombre}! Estás en nivel {nivel}\")\n\nbienvenida(\"Pylearn\", 99)",
    "options": [
      "¡Hola nombre! Estás en nivel nivel",
      "¡Hola Pylearn! Estás en nivel 99",
      "bienvenida(Pylearn, 99)",
      "Error: demasiados parámetros"
    ],
    "hint": "Pista: Revisa los conceptos de Parámetros y argumentos.",
    "explanation": "Al llamar bienvenida(\"Pylearn\", 99), nombre recibe \"Pylearn\" y nivel recibe 99. El f-string los inserta en el texto. Los parámetros son como los espacios en blanco de la receta ¡que tú llenan! 🎮",
    "correctAnswer": "¡Hola Pylearn! Estás en nivel 99",
    "orderIndex": 172,
    "coins": 5,
    "xp": 10,
    "theme": "🎮 Saludar al jugador",
    "pytoReaction": "¡Nivel 99! Pylearn está demasiado cerca del jefe final 🐍🎮"
  },
  {
    "id": 173,
    "title": "Funciones: *args",
    "description": "Pylearn quiere hacer una función que acepte cualquier cantidad de toppings. ¿Cuál funciona?",
    "topic": "Funciones básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "Pylearn quiere hacer una función que acepte cualquier cantidad de toppings. ¿Cuál funciona?",
    "options": [
      "def pizza(toppings[]):",
      "def pizza(*toppings):",
      "def pizza(toppings...):",
      "def pizza(all toppings):"
    ],
    "hint": "Pista: Revisa los conceptos de *args.",
    "explanation": "*args (el nombre es convención, el * es lo importante) captura todos los argumentos posicionales en una tupla. Puedes pasar 0, 1 o 100 ingredientes. ¡La pizzería de Pylearn acepta todo! 🍕",
    "correctAnswer": "def pizza(*toppings):",
    "orderIndex": 173,
    "coins": 5,
    "xp": 10,
    "theme": "🍕 Pizzería con ingredientes ilimitados",
    "pytoReaction": "¡Pizza personalizada infinita! Pylearn pide 15 toppings 🐍🍕"
  },
  {
    "id": 174,
    "title": "Funciones: *args",
    "description": "¿Qué imprime el presentador de la banda?",
    "topic": "Funciones básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "def presentar_banda(*musicos):\n    print(f\"En escena: {len(musicos)} músicos\")\n    for m in musicos:\n        print(f\"- {m}\")\n\npresentar_banda(\"Freddie\", \"Brian\", \"Roger\")",
    "options": [
      "En escena: musicos músicos\\n- Freddie...",
      "En escena: 3 músicos\\n- Freddie\\n- Brian\\n- Roger",
      "En escena: (Freddie, Brian, Roger) músicos",
      "Error: demasiados argumentos"
    ],
    "hint": "Pista: Revisa los conceptos de *args.",
    "explanation": "*musicos captura los 3 argumentos como tupla (\"Freddie\", \"Brian\", \"Roger\"). len() la mide, el for la itera. ¡Queen completo en escena! 🎸",
    "correctAnswer": "En escena: 3 músicos\n- Freddie\n- Brian\n- Roger",
    "orderIndex": 174,
    "coins": 5,
    "xp": 10,
    "theme": "🎸 Banda de rock con músicos variables",
    "pytoReaction": "¡We will rock you! Pylearn toca batería en la banda 🐍🥁"
  },
  {
    "id": 175,
    "title": "Funciones: **kwargs",
    "description": "Pylearn crea perfiles con atributos personalizados usando **kwargs:",
    "topic": "Funciones básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "def crear_mago(___atributos):\n    for key, val in atributos.items():\n        print(f\"{key}: {val}\")\n\ncrear_mago(nombre=\"Gandalf\", color=\"gris\", nivel=100)",
    "options": [
      "**",
      "*",
      "...",
      "->",
      "//",
      "@@"
    ],
    "hint": "Pista: Revisa los conceptos de **kwargs.",
    "explanation": "**kwargs captura argumentos keyword (clave=valor) en un diccionario. * captura posicionales en tupla, ** captura keywords en dict. El nombre 'atributos' es arbitrario, los ** son lo importante. 🧙",
    "correctAnswer": "**",
    "orderIndex": 175,
    "coins": 5,
    "xp": 10,
    "theme": "🧙 Perfil mágico personalizable",
    "pytoReaction": "¡Gandalf creado! Pylearn domina los kwargs mágicos 🐍🧙"
  },
  {
    "id": 176,
    "title": "Funciones: Return múltiple",
    "description": "¿Qué imprimen las coordenadas del satélite de Pylearn?",
    "topic": "Funciones básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "def calcular_orbita(radio):\n    x = radio * 2\n    y = radio * 3\n    return x, y\n\ncoordx, coordy = calcular_orbita(10)\nprint(f\"X:{coordx} Y:{coordy}\")",
    "options": [
      "X:10 Y:10",
      "X:20 Y:30",
      "X:(20,30) Y:(20,30)",
      "Error: return solo puede devolver un valor"
    ],
    "hint": "Pista: Revisa los conceptos de Return múltiple.",
    "explanation": "Python permite retornar múltiples valores separados por coma — realmente retorna una tupla (20, 30). Al asignar coordx, coordy = ... se hace unpacking automático. ¡El satélite está en X:20 Y:30! 🌙",
    "correctAnswer": "X:20 Y:30",
    "orderIndex": 176,
    "coins": 5,
    "xp": 10,
    "theme": "🌙 Calculadora de coordenadas espaciales",
    "pytoReaction": "¡Satélite en órbita perfecta! Pylearn controla la NASA 🐍🚀"
  },
  {
    "id": 177,
    "title": "Funciones: Docstrings",
    "description": "¿Cuál es el propósito del texto entre las tres comillas en esta función?",
    "topic": "Funciones básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "def calcular_imc(peso, altura):\n    \"\"\"Calcula el IMC dado peso en kg y altura en metros.\n    Retorna el valor float del IMC.\"\"\"\n    return peso / (altura ** 2)",
    "options": [
      "Es un comentario ignorado igual que #",
      "Es un docstring — documentación accesible con help() y en IDEs",
      "Es obligatorio para que la función funcione",
      "Es para mostrar al usuario cuando la función falla"
    ],
    "hint": "Pista: Revisa los conceptos de Docstrings.",
    "explanation": "Los docstrings (\"\"\"...\"\"\") son documentación oficial de la función. Se acceden con help(calcular_imc) o función.__doc__. Los IDEs los muestran como tooltip. Son mejores que # porque son accesibles en runtime. 📚",
    "correctAnswer": "Es un docstring — documentación accesible con help() y en IDEs",
    "orderIndex": 177,
    "coins": 5,
    "xp": 10,
    "theme": "📚 Manual del programador profesional",
    "pytoReaction": "¡Código documentado! Pylearn es un programador profesional 🐍📚"
  },
  {
    "id": 178,
    "title": "Funciones: Return múltiple",
    "description": "El analizador retorna incorrectamente. ¿Cuál es el error?",
    "topic": "Funciones básicas - Misión 1",
    "difficulty": "beginner",
    "type": "bug",
    "question": "def analizar_record(tiempos):\n    mejor = min(tiempos)\n    peor = max(tiempos)\n    promedio = sum(tiempos) / len(tiempos)\n    return mejor, peor\n    return promedio\n\nresultados = analizar_record([52.1, 49.3, 51.8])",
    "options": [
      "min() y max() no funcionan en listas de floats",
      "Solo el primer return se ejecuta — el segundo nunca llega",
      "No puedes tener dos returns en una función",
      "promedio debería calcularse antes de mejor y peor"
    ],
    "hint": "Pista: Revisa los conceptos de Return múltiple.",
    "explanation": "return termina la función inmediatamente. Todo lo que venga después del primer return nunca se ejecuta. Fix: return mejor, peor, promedio en una sola línea. ¡Los 3 valores retornados juntos! 🏊",
    "correctAnswer": "Solo el primer return se ejecuta — el segundo nunca llega",
    "orderIndex": 178,
    "coins": 5,
    "xp": 10,
    "theme": "🏊 Analizador de records de natación",
    "pytoReaction": "¡Bug del return encontrado! Pylearn ahora retorna los 3 valores 🐍🏊"
  },
  {
    "id": 179,
    "title": "Funciones: Funciones como argumentos",
    "description": "¿Qué imprime el clasificador de mensajes del bot?",
    "topic": "Funciones básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "def procesar(texto, transformacion):\n    return transformacion(texto)\n\nresultado = procesar(\"hola pyto\", str.upper)\nprint(resultado)",
    "options": [
      "hola pyto",
      "HOLA PYTO",
      "str.upper",
      "Error: str.upper no es callable"
    ],
    "hint": "Pista: Revisa los conceptos de Funciones como argumentos.",
    "explanation": "Las funciones son objetos en Python — puedes pasarlas como argumentos sin llamarlas (sin ()). str.upper es la función sin invocar. procesar() la llama internamente con el texto. ¡El bot clasifica en mayúsculas! 🤖",
    "correctAnswer": "HOLA PYTO",
    "orderIndex": 179,
    "coins": 5,
    "xp": 10,
    "theme": "🤖 Bot clasificador de mensajes",
    "pytoReaction": "¡Funciones como parámetros! Pylearn descubrió la magia funcional 🐍🤖"
  },
  {
    "id": 180,
    "title": "Funciones: map()",
    "description": "¿Cuál es la forma más pythónica de convertir una lista de Celsius a Fahrenheit?",
    "topic": "Funciones básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "celsius = [0, 20, 37, 100]\n# Convertir cada uno: F = C * 9/5 + 32",
    "options": [
      "for c in celsius: fahrenheit.append(c * 9/5 + 32)",
      "fahrenheit = map(lambda c: c * 9/5 + 32, celsius)",
      "fahrenheit = celsius.convert(9/5, 32)",
      "fahrenheit = celsius * 9/5 + 32"
    ],
    "hint": "Pista: Revisa los conceptos de map().",
    "explanation": "map(función, iterable) aplica la función a cada elemento. Con lambda crea la función inline. Para obtener una lista: list(map(...)). Es más expresivo que un for loop explícito. 🌡️",
    "correctAnswer": "fahrenheit = map(lambda c: c * 9/5 + 32, celsius)",
    "orderIndex": 180,
    "coins": 5,
    "xp": 10,
    "theme": "🌡️ Convirtiendo temperaturas",
    "pytoReaction": "¡Temperaturas convertidas! Pylearn ya entiende el clima de EE.UU. 🐍🌡️"
  },
  {
    "id": 181,
    "title": "Funciones: filter()",
    "description": "Pylearn filtra solo los jugadores de nivel 50 o más para el torneo elite:",
    "topic": "Funciones básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "jugadores = [15, 72, 43, 91, 8, 55]\nelite = list(___(lambda n: n >= 50, jugadores))\nprint(elite)  # → [72, 91, 55]",
    "options": [
      "filter",
      "map",
      "reduce",
      "select",
      "where",
      "find"
    ],
    "hint": "Pista: Revisa los conceptos de filter().",
    "explanation": "filter(función_condición, iterable) retorna solo los elementos donde la función retorna True. Combina bien con lambda. list() convierte el resultado a lista. ¡Solo los de nivel 50+ entran al torneo! 🎮",
    "correctAnswer": "filter",
    "orderIndex": 181,
    "coins": 5,
    "xp": 10,
    "theme": "🎮 Filtrando jugadores por nivel",
    "pytoReaction": "¡Elite seleccionada! Pylearn con 72 de nivel entra fácil 🐍🎮"
  }
];

