import type { ExerciseData } from "../types";

export const topicExercises: ExerciseData[] = [
  {
    "id": 182,
    "title": "Funciones: Funciones anidadas",
    "description": "¿Qué imprime el generador de contraseñas de Pylearn?",
    "topic": "Funciones básicas - Misión 2",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "def generar_contra(base):\n    def agregar_seguridad(texto):\n        return texto + \"!@#\"\n    contra_segura = agregar_seguridad(base.upper())\n    return contra_segura\n\nprint(generar_contra(\"pyto\"))",
    "options": [
      "pyto",
      "PYTO",
      "pyto!@#",
      "PYTO!@#"
    ],
    "hint": "Pista: Revisa los conceptos de Funciones anidadas.",
    "explanation": "Las funciones pueden definirse dentro de otras. agregar_seguridad es local a generar_contra. El flujo: 'pyto'.upper() = 'PYTO', luego agregar_seguridad('PYTO') = 'PYTO!@#'. ¡Contraseña segura! 🔐",
    "correctAnswer": "PYTO!@#",
    "orderIndex": 182,
    "coins": 5,
    "xp": 10,
    "theme": "🔐 Generador de contraseña segura",
    "pytoReaction": "¡PYTO!@# es ultra segura! Ningún hacker la descifra 🐍🔐"
  },
  {
    "id": 183,
    "title": "Funciones: Parámetros por defecto",
    "description": "La función de tacos falla al definirse. ¿Cuál es el error?",
    "topic": "Funciones básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "bug",
    "question": "def hacer_taco(salsa=\"picante\", proteina, tortilla=\"maiz\"):\n    return f\"Taco de {proteina} con {salsa}\"",
    "options": [
      "return debería ser print",
      "Los parámetros con default van al FINAL",
      "salsa no puede tener comillas",
      "proteina necesita valor por defecto"
    ],
    "hint": "Pista: Revisa los conceptos de Parámetros por defecto.",
    "explanation": "Los parámetros obligatorios (sin default) SIEMPRE van antes que los opcionales (con default). Correcto: def hacer_taco(proteina, salsa=\"picante\", tortilla=\"maiz\"). ¡El orden importa! 🌮",
    "correctAnswer": "Los parámetros con default van al FINAL",
    "orderIndex": 183,
    "coins": 12,
    "xp": 20,
    "theme": "🌮 Taquería mal ordenada",
    "pytoReaction": "¡Taquería arreglada! Pylearn pide carnitas sin salsa 🐍🌮"
  },
  {
    "id": 184,
    "title": "Funciones: Parámetros por defecto",
    "description": "¿Qué imprime el sistema de creación de personajes?",
    "topic": "Funciones básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "predict_output",
    "question": "def crear_heroe(nombre, clase=\"Mago\", nivel=1):\n    print(f\"{nombre} | {clase} | Nv.{nivel}\")\n\ncrear_heroe(\"Pylearn\", nivel=99)\ncrear_heroe(\"Ana\")",
    "options": [
      "Pylearn | Mago | Nv.99\nAna | Mago | Nv.1",
      "Pylearn | Mago | Nv.1\nAna | Mago | Nv.99",
      "Pylearn | nivel | Nv.99\nAna | Mago | Nv.1",
      "Error: nivel=99 está fuera de lugar"
    ],
    "hint": "Pista: Revisa los conceptos de Parámetros por defecto.",
    "explanation": "Pylearn usa argumento keyword (nivel=99) saltándose 'clase' → usa el default 'Mago'. Ana no pasa nada → usa todos los defaults. ¡Los kwargs son súper flexibles! ⚔️",
    "correctAnswer": "Pylearn | Mago | Nv.99\nAna | Mago | Nv.1",
    "orderIndex": 184,
    "coins": 12,
    "xp": 20,
    "theme": "⚔️ RPG con stats base",
    "pytoReaction": "¡Pylearn saltó directo a nivel 99! El truco del argumento keyword 🐍⚔️"
  },
  {
    "id": 185,
    "title": "Funciones: Scope",
    "description": "¿Qué pasa cuando el agente Pylearn intenta acceder al secreto clasificado?",
    "topic": "Funciones básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "multiple_choice",
    "question": "def mision_secreta():\n    contrasena = \"PylearnEsElMejor123\"\n    return \"Misión completada\"\n\nmision_secreta()\nprint(contrasena)",
    "options": [
      "Imprime: PylearnEsElMejor123",
      "Imprime: None",
      "Error: contrasena no existe fuera de la función",
      "Imprime: contrasena"
    ],
    "hint": "Pista: Revisa los conceptos de Scope.",
    "explanation": "Las variables dentro de una función son LOCALES: solo existen ahí dentro. Al salir de la función, desaparecen. Para usarla afuera → retornarla con return. ¡El secreto está a salvo! 🔐",
    "correctAnswer": "Error: contrasena no existe fuera de la función",
    "orderIndex": 185,
    "coins": 12,
    "xp": 20,
    "theme": "🔐 Variable clasificada",
    "pytoReaction": "¡Acceso denegado! Hasta Pylearn respeta el scope 🐍🔐"
  },
  {
    "id": 186,
    "title": "Funciones: Closure",
    "description": "¿Qué imprime el generador de multiplicadores del RPG?",
    "topic": "Funciones básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "predict_output",
    "question": "def hacer_multiplicador(factor):\n    def multiplicar(n):\n        return n * factor\n    return multiplicar\n\ndanio_doble = hacer_multiplicador(2)\ndanio_triple = hacer_multiplicador(3)\nprint(danio_doble(50))\nprint(danio_triple(50))",
    "options": [
      "100\\n150",
      "50\\n50",
      "2\\n3",
      "100\\n150 — pero solo si factor es global"
    ],
    "hint": "Pista: Revisa los conceptos de Closure.",
    "explanation": "Este es un closure: multiplicar 'recuerda' el valor de factor aunque hacer_multiplicador ya terminó. danio_doble es una función con factor=2 'atrapado'. danio_triple tiene factor=3. ¡RPG con closures! 🎯",
    "correctAnswer": "100\n150",
    "orderIndex": 186,
    "coins": 12,
    "xp": 20,
    "theme": "🎯 Generador de multiplicadores RPG",
    "pytoReaction": "¡150 de daño triple! Pylearn descubrió los closures 🐍🎯"
  },
  {
    "id": 187,
    "title": "Funciones: Type hints",
    "description": "Pylearn agrega type hints a su función científica para documentarla mejor:",
    "topic": "Funciones básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "fill_blank",
    "question": "def calcular_velocidad(distancia: ___, tiempo: float) -> float:\n    return distancia / tiempo\n\nresult = calcular_velocidad(100.0, 9.58)\nprint(f\"{result:.2f} m/s\")",
    "options": [
      "float",
      "int",
      "str",
      "number",
      "Float",
      "double"
    ],
    "hint": "Pista: Revisa los conceptos de Type hints.",
    "explanation": "Los type hints (param: tipo) son opcionales pero mejoran la legibilidad. -> float indica el tipo de retorno. Python NO los aplica en runtime (no es estrictamente tipado), pero los IDEs y mypy sí los usan. 🔬",
    "correctAnswer": "float",
    "orderIndex": 187,
    "coins": 12,
    "xp": 20,
    "theme": "🔬 Laboratorio de precisión de Pylearn",
    "pytoReaction": "¡Usain Bolt hace 10.44 m/s! Pylearn lo calcula con type hints 🐍🔬"
  },
  {
    "id": 188,
    "title": "Funciones: Decoradores básico",
    "description": "¿Qué imprime el decorador de Pylearn?",
    "topic": "Funciones básicas - Misión 2",
    "difficulty": "intermediate",
    "type": "predict_output",
    "question": "def anunciar(func):\n    def wrapper():\n        print(\"Iniciando...\")\n        func()\n        print(\"Listo!\")\n    return wrapper\n\n@anunciar\ndef lanzar_cohete():\n    print(\"DESPEGUE\")\n\nlanzar_cohete()",
    "options": [
      "DESPEGUE",
      "Iniciando...\\nDESPEGUE\\nListo!",
      "Iniciando...\\nListo!",
      "Error: @ no es sintaxis válida"
    ],
    "hint": "Pista: Revisa los conceptos de Decoradores básico.",
    "explanation": "@anunciar es syntactic sugar para lanzar_cohete = anunciar(lanzar_cohete). Al llamar lanzar_cohete(), en realidad llama wrapper() que envuelve la función original con los prints. ¡Decoradores: superpoderes para funciones! ⚡",
    "correctAnswer": "Iniciando...\nDESPEGUE\nListo!",
    "orderIndex": 188,
    "coins": 12,
    "xp": 20,
    "theme": "⚡ Medidor de velocidad de código",
    "pytoReaction": "¡DESPEGUE con estilo! Pylearn descubrió los decoradores 🐍⚡"
  },
  {
    "id": 189,
    "title": "Funciones: lambda",
    "description": "Pylearn crea una función turbo de una sola línea para calcular el daño crítico:",
    "topic": "Funciones básicas - Misión 2",
    "difficulty": "advanced",
    "type": "fill_blank",
    "question": "critico = ___ daño: daño * 2.5\nprint(critico(100))  # → 250.0",
    "options": [
      "lambda",
      "def",
      "func",
      "fn",
      "mini",
      "quick"
    ],
    "hint": "Pista: Revisa los conceptos de lambda.",
    "explanation": "lambda crea funciones en UNA sola línea. Sintaxis: lambda parámetros: expresión. Son perfectas para funciones simples que usas una sola vez. ¡250 de daño crítico! ⚡",
    "correctAnswer": "lambda",
    "orderIndex": 189,
    "coins": 25,
    "xp": 35,
    "theme": "⚡ Función turbo",
    "pytoReaction": "¡CRÍTICO! Lambda es el golpe más rápido de Python 🐍⚡"
  },
  {
    "id": 190,
    "title": "Funciones: Memoización manual",
    "description": "¿Por qué la versión con caché es muchísimo más rápida para fibonacci(40)?",
    "topic": "Funciones básicas - Misión 2",
    "difficulty": "advanced",
    "type": "multiple_choice",
    "question": "cache = {}\ndef fib_rapido(n):\n    if n in cache:\n        return cache[n]\n    if n <= 1:\n        return n\n    resultado = fib_rapido(n-1) + fib_rapido(n-2)\n    cache[n] = resultado\n    return resultado",
    "options": [
      "Porque usa un diccionario en lugar de una lista",
      "Porque guarda resultados ya calculados y no los recalcula",
      "Porque el if n <= 1 es más eficiente",
      "Porque Python optimiza automáticamente la recursión"
    ],
    "hint": "Pista: Revisa los conceptos de Memoización manual.",
    "explanation": "Memoización = guardar resultados en cache dict. Sin cache, fib(40) calcula fib(39)+fib(38), fib(39) calcula fib(38)+fib(37)... repitiendo millones de cálculos. Con cache: cada valor se calcula UNA vez. De exponencial a lineal. ⚡",
    "correctAnswer": "Porque guarda resultados ya calculados y no los recalcula",
    "orderIndex": 190,
    "coins": 25,
    "xp": 35,
    "theme": "⚡ Fibonacci ultra rápido",
    "pytoReaction": "¡fib(40) en microsegundos! Pylearn entiende la memoización 🐍⚡"
  },
  {
    "id": 191,
    "title": "Funciones: Funciones recursivas con acumulador",
    "description": "¿Qué retorna la función de suma recursiva del tesoro?",
    "topic": "Funciones básicas - Misión 2",
    "difficulty": "advanced",
    "type": "multiple_choice",
    "question": "def sumar_tesoro(monedas, acumulado=0):\n    if not monedas:\n        return acumulado\n    return sumar_tesoro(monedas[1:], acumulado + monedas[0])\n\nprint(sumar_tesoro([10, 20, 30, 40]))",
    "options": [
      "10",
      "100",
      "40",
      "Error: recursión infinita"
    ],
    "hint": "Pista: Revisa los conceptos de Funciones recursivas con acumulador.",
    "explanation": "Recursión con acumulador. Caso base: lista vacía → retorna acumulado. Recursivo: llama con [20,30,40] y acumulado=10, luego [30,40] y 30, luego [40] y 60, luego [] y 100. 10+20+30+40=100. 🏰",
    "correctAnswer": "100",
    "orderIndex": 191,
    "coins": 25,
    "xp": 35,
    "theme": "🏰 Suma recursiva del tesoro del castillo",
    "pytoReaction": "¡100 monedas de tesoro! El castillo de Pylearn es rico 🐍🏰"
  },
  {
    "id": 192,
    "title": "Funciones: Función generadora de funciones",
    "description": "¿Qué hechizos produce la fábrica de Pylearn?",
    "topic": "Funciones básicas - Misión 2",
    "difficulty": "advanced",
    "type": "predict_output",
    "question": "def fabrica_hechizo(elemento):\n    def lanzar(objetivo):\n        return f\"{elemento} golpea a {objetivo} por {len(elemento)*10} de daño\"\n    return lanzar\n\nfuego = fabrica_hechizo(\"fuego\")\nhielo = fabrica_hechizo(\"hielo\")\nprint(fuego(\"dragón\"))\nprint(hielo(\"demonio\"))",
    "options": [
      "fuego golpea a dragón por 50 de daño\\nhielo golpea a demonio por 50 de daño",
      "fuego golpea a dragón por 40 de daño\\nhielo golpea a demonio por 50 de daño",
      "fuego golpea a dragón por 50 de daño\\nhielo golpea a demonio por 60 de daño",
      "Error: len() no funciona dentro del closure"
    ],
    "hint": "Pista: Revisa los conceptos de Función generadora de funciones.",
    "explanation": "'fuego' tiene 5 letras → 5*10=50 daño. 'hielo' tiene 5 letras → 5*10=50 daño. Cada función cierre recuerda su propio 'elemento'. Closures en acción: cada hechizo tiene su estado interno capturado. ⚗️",
    "correctAnswer": "fuego golpea a dragón por 50 de daño\nhielo golpea a demonio por 50 de daño",
    "orderIndex": 192,
    "coins": 25,
    "xp": 35,
    "theme": "⚗️ Fábrica de hechizos del laboratorio",
    "pytoReaction": "¡Fábrica de hechizos activa! Pylearn lanza 50 de daño con cada elemento 🐍⚗️"
  },
  {
    "id": 193,
    "title": "Funciones: Recursión",
    "description": "¿Qué imprime la función recursiva del espejo de Pylearn?",
    "topic": "Funciones básicas - Misión 2",
    "difficulty": "tryhard",
    "type": "predict_output",
    "question": "def espejo(n):\n    if n == 0:\n        print(\"¡Me ví!\")\n        return\n    print(f\"Reflejo {n}\")\n    espejo(n - 1)\n\nespejo(3)",
    "options": [
      "Reflejo 3\nReflejo 2\nReflejo 1\n¡Me ví!",
      "¡Me ví!\nReflejo 1\nReflejo 2\nReflejo 3",
      "Reflejo 1\nReflejo 2\nReflejo 3\n¡Me ví!",
      "Loop infinito"
    ],
    "hint": "Pista: Revisa los conceptos de Recursión.",
    "explanation": "La función se llama a sí misma con n-1. Primero imprime n, luego se llama. Cuando n llega a 0, imprime '¡Me ví!' y para (caso base). Sin caso base → loop infinito 💥",
    "correctAnswer": "Reflejo 3\nReflejo 2\nReflejo 1\n¡Me ví!",
    "orderIndex": 193,
    "coins": 50,
    "xp": 80,
    "theme": "🌀 El espejo infinito",
    "pytoReaction": "¡Pylearn se vio en el espejo y se asustó! Era demasiado hermoso 🐍🌀"
  }
];

