import type { ExerciseData } from "../types";

export const topicExercises: ExerciseData[] = [
  {
    "id": 194,
    "title": "Diccionarios: Crear diccionarios",
    "description": "Creas la ficha de tu personaje RPG. ¿Cuál es la sintaxis correcta de un diccionario?",
    "topic": "Diccionarios básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "Creas la ficha de tu personaje RPG. ¿Cuál es la sintaxis correcta de un diccionario?",
    "options": [
      "heroe = [\"nombre\":\"Pylearn\", \"clase\":\"Mago\"]",
      "heroe = {\"nombre\":\"Pylearn\", \"clase\":\"Mago\"}",
      "heroe = (\"nombre\":\"Pylearn\", \"clase\":\"Mago\")",
      "heroe = {nombre=\"Pylearn\", clase=\"Mago\"}"
    ],
    "hint": "Pista: Revisa los conceptos de Crear diccionarios.",
    "explanation": "¡Los diccionarios usan llaves {}! Cada par es \"clave\": valor separado por coma. No confundir: [] son listas, () son tuplas/funciones, {} con : son diccionarios. ¡Ficha lista! 🐉",
    "correctAnswer": "heroe = {\"nombre\":\"Pylearn\", \"clase\":\"Mago\"}",
    "orderIndex": 194,
    "coins": 5,
    "xp": 10,
    "theme": "🐉 Ficha del héroe RPG",
    "pytoReaction": "¡Pylearn el Mago ha entrado al servidor! 🐍🐉"
  },
  {
    "id": 195,
    "title": "Diccionarios: Acceso a valores",
    "description": "¿Qué número aparece al consultar el ataque de Pylearn?",
    "topic": "Diccionarios básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "heroe = {\"nombre\":\"Pylearn\", \"ataque\":9000, \"defensa\":10}\nprint(heroe[\"ataque\"])",
    "options": [
      "\"ataque\"",
      "9000",
      "ataque: 9000",
      "{\"ataque\": 9000}"
    ],
    "hint": "Pista: Revisa los conceptos de Acceso a valores.",
    "explanation": "Se accede al valor con dict[\"clave\"]. Retorna directamente el valor (9000), NO la clave ni el par completo. ¡El ataque de Pylearn pasa los 9000! ¿Qué? ¡¡NUEVE MIIIIL!! ⚔️",
    "correctAnswer": "9000",
    "orderIndex": 195,
    "coins": 5,
    "xp": 10,
    "theme": "📊 Consultando stats",
    "pytoReaction": "¡El poder de Pylearn rompe el medidor! 🐍💥"
  },
  {
    "id": 196,
    "title": "Diccionarios: items()",
    "description": "Pylearn revisa TODO su inventario (objeto Y cantidad):",
    "topic": "Diccionarios básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "inventario = {\"espada\":1, \"pociones\":5, \"oro\":999}\nfor objeto, cantidad in inventario.___():\n    print(f\"{objeto}: {cantidad}\")",
    "options": [
      "items",
      "pairs",
      "entries",
      "values",
      "keys",
      "all"
    ],
    "hint": "Pista: Revisa los conceptos de items().",
    "explanation": ".items() da pares (clave, valor). .keys() solo da las claves. .values() solo los valores. Para recorrer AMBOS al mismo tiempo: siempre .items() 🗺️",
    "correctAnswer": "items",
    "orderIndex": 196,
    "coins": 5,
    "xp": 10,
    "theme": "🗺️ Inventario del aventurero",
    "pytoReaction": "¡999 de oro! Pylearn está forrado 🐍💰"
  },
  {
    "id": 197,
    "title": "Diccionarios: .update()",
    "description": "Pylearn recibe power-ups y actualiza varias stats a la vez. ¿Cuál método actualiza múltiples claves de una vez?",
    "topic": "Diccionarios básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "stats = {\"vida\":100, \"ataque\":50, \"defensa\":30}\npowerup = {\"ataque\":80, \"velocidad\":45}",
    "options": [
      "stats.add(powerup)",
      "stats.update(powerup)",
      "stats.merge(powerup)",
      "stats.extend(powerup)"
    ],
    "hint": "Pista: Revisa los conceptos de .update().",
    "explanation": ".update(otro_dict) agrega o actualiza TODAS las claves del otro dict. ataque pasa de 50 a 80 (actualiza), velocidad=45 se agrega (nueva). ¡Stats actualizadas en una sola línea! 👾",
    "correctAnswer": "stats.update(powerup)",
    "orderIndex": 197,
    "coins": 5,
    "xp": 10,
    "theme": "👾 Actualizando estadísticas del personaje",
    "pytoReaction": "¡Stats actualizadas! Pylearn es imparable ahora 🐍👾"
  },
  {
    "id": 198,
    "title": "Diccionarios: .update()",
    "description": "¿Cuál es el estado de la misión después del update?",
    "topic": "Diccionarios básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "mision = {\"nave\":\"Falcon9\", \"estado\":\"prep\", \"tripulacion\":3}\nmision.update({\"estado\":\"lanzado\", \"altitud_km\":400})\nprint(mision[\"estado\"])\nprint(mision[\"altitud_km\"])",
    "options": [
      "prep\\n400",
      "lanzado\\nError",
      "lanzado\\n400",
      "Error: no se puede actualizar estado"
    ],
    "hint": "Pista: Revisa los conceptos de .update().",
    "explanation": ".update() modifica en el lugar. 'estado' se actualiza de 'prep' a 'lanzado'. 'altitud_km':400 se agrega como nueva clave. Las otras claves (nave, tripulacion) no cambian. ¡La misión está en curso! 🚀",
    "correctAnswer": "lanzado\n400",
    "orderIndex": 198,
    "coins": 5,
    "xp": 10,
    "theme": "🚀 Actualización de misión espacial",
    "pytoReaction": "¡Falcon9 en órbita a 400km! Pylearn es astronauta 🐍🚀"
  },
  {
    "id": 199,
    "title": "Diccionarios: .pop() en dict",
    "description": "El director elimina al actor que se portó mal y guarda su nombre:",
    "topic": "Diccionarios básicas - Misión 1",
    "difficulty": "beginner",
    "type": "fill_blank",
    "question": "reparto = {\"protagonista\":\"Pylearn\", \"villano\":\"DramáticoBot\", \"extra\":\"Anónimo\"}\nbaneado = reparto.___(\"villano\")\nprint(baneado)   # → DramáticoBot",
    "options": [
      "pop",
      "remove",
      "delete",
      "del",
      "kick",
      "exclude"
    ],
    "hint": "Pista: Revisa los conceptos de .pop() en dict.",
    "explanation": "dict.pop(clave) elimina y RETORNA el valor de esa clave. Si la clave no existe → KeyError. Puedes dar default: dict.pop('clave', None) para evitar el error. ¡DramáticoBot fue eliminado del reparto! 🎭",
    "correctAnswer": "pop",
    "orderIndex": 199,
    "coins": 5,
    "xp": 10,
    "theme": "🎭 Eliminando actor del reparto",
    "pytoReaction": "¡DramáticoBot eliminado! El set de Pylearn es zona libre de drama 🐍🎭"
  },
  {
    "id": 200,
    "title": "Diccionarios: del en dict",
    "description": "¿Qué queda en el perfil después de borrar los datos sensibles?",
    "topic": "Diccionarios básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "perfil = {\"usuario\":\"Pylearn\", \"password\":\"1234\", \"email\":\"pyto@snake.py\"}\ndel perfil[\"password\"]\nprint(list(perfil.keys()))",
    "options": [
      "[\"usuario\", \"password\", \"email\"]",
      "[\"usuario\", \"email\"]",
      "[\"password\"]",
      "Error: del no funciona en dicts"
    ],
    "hint": "Pista: Revisa los conceptos de del en dict.",
    "explanation": "'del dict[clave]' elimina la clave permanentemente. No retorna nada (a diferencia de .pop()). .keys() retorna las claves restantes. ¡El password fue borrado por seguridad! 🔐",
    "correctAnswer": "[\"usuario\", \"email\"]",
    "orderIndex": 200,
    "coins": 5,
    "xp": 10,
    "theme": "🔐 Borrando datos confidenciales",
    "pytoReaction": "¡Password eliminado! La seguridad de Pylearn es prioritaria 🐍🔐"
  },
  {
    "id": 201,
    "title": "Diccionarios: .values()",
    "description": "¿Cómo suma Pylearn todos los precios del presupuesto sin pasar por las claves?",
    "topic": "Diccionarios básicas - Misión 1",
    "difficulty": "beginner",
    "type": "multiple_choice",
    "question": "gastos = {\"alquiler\":800, \"comida\":250, \"internet\":50, \"netflix\":15}\ntotal = sum(gastos._____())",
    "options": [
      "keys()",
      "values()",
      "items()",
      "nums()"
    ],
    "hint": "Pista: Revisa los conceptos de .values().",
    "explanation": ".values() retorna todos los valores del dict como una vista iterable. sum() puede sumar directamente desde esa vista. sum(gastos.values()) = 800+250+50+15 = 1115. ¡El presupuesto de Pylearn calculado! 💰",
    "correctAnswer": "values()",
    "orderIndex": 201,
    "coins": 5,
    "xp": 10,
    "theme": "💰 Calculando el total del presupuesto",
    "pytoReaction": "¡S/1,115 de gastos! Pylearn necesita más PylearnCrystals 🐍💰"
  },
  {
    "id": 202,
    "title": "Diccionarios: Patrón de conteo",
    "description": "¿Cuántas canciones de reggaeton tiene la playlist de Pylearn?",
    "topic": "Diccionarios básicas - Misión 1",
    "difficulty": "beginner",
    "type": "predict_output",
    "question": "playlist = [\"pop\", \"reggaeton\", \"pop\", \"rock\", \"reggaeton\", \"reggaeton\"]\nconteo = {}\nfor genero in playlist:\n    conteo[genero] = conteo.get(genero, 0) + 1\nprint(conteo[\"reggaeton\"])",
    "options": [
      "1",
      "2",
      "3",
      "6"
    ],
    "hint": "Pista: Revisa los conceptos de Patrón de conteo.",
    "explanation": "El patrón conteo.get(key, 0) + 1 es el estándar para contar frecuencias. Si la clave no existe devuelve 0 (default), si existe devuelve el valor actual, y en ambos casos suma 1. Reggaeton aparece 3 veces. 🎵",
    "correctAnswer": "3",
    "orderIndex": 202,
    "coins": 5,
    "xp": 10,
    "theme": "🎵 Contando géneros musicales del playlist",
    "pytoReaction": "¡3 reggaetones! Pylearn tiene muy buen gusto musical 🐍🎵"
  },
  {
    "id": 203,
    "title": "Diccionarios: KeyError y .get()",
    "description": "El juego de Pylearn crashea al buscar una habilidad. ¿Por qué?",
    "topic": "Diccionarios básicas - Misión 1",
    "difficulty": "intermediate",
    "type": "bug",
    "question": "habilidades = {\"fuego\":50, \"hielo\":30, \"rayo\":45}\ndaño = habilidades[\"veneno\"]\nprint(f\"Daño: {daño}\")",
    "options": [
      "habilidades no es un dict válido",
      "\"veneno\" no existe en el dict → KeyError",
      "daño no puede ser un número",
      "El f-string tiene un error de sintaxis"
    ],
    "hint": "Pista: Revisa los conceptos de KeyError y .get().",
    "explanation": "Acceder con [] a una clave que no existe → KeyError y el programa crashea. Solución segura: habilidades.get(\"veneno\", 0) devuelve 0 si no existe en lugar de crashear. ¡Siempre .get() cuando hay duda! 🛡️",
    "correctAnswer": "\"veneno\" no existe en el dict → KeyError",
    "orderIndex": 203,
    "coins": 12,
    "xp": 20,
    "theme": "💥 Habilidad inexistente",
    "pytoReaction": "¡Pylearn aprendió a usar .get() para no morir más! 🐍🛡️"
  }
];

